(function(){
'use strict';
function render(ctx){
 const {state,M,$,tex,fmt,header,svg,color,save,checkpoint,rerender}=ctx,C=window.ConvolutionMath,g=state.graph,n=g.nodes.length;
 const en=state.lang==='en',say=(zh,english)=>en?english:zh;
 const s=state.convolutionLab||(state.convolutionLab={alphaFraction:.5,steps:1,selected:0});
 window.LabSession.refreshWeights(M,state);
 const analysis=M.analyze(g.nodes,g.edges,'unnormalized'),options=C.settingsFor(analysis,s);
 Object.assign(s,{alphaFraction:options.alphaFraction,steps:options.steps,selected:Math.min(Math.max(0,Math.floor(Number.isFinite(s.selected)?s.selected:0)),Math.max(0,n-1))});
 const fresh=g.nodes.every(p=>!Number.isFinite(p.signal));
 g.nodes.forEach((p,i)=>{if(!Number.isFinite(p.signal))p.signal=fresh&&i===0?1:0;});
 const nodeWord=say('節點','Node'),xs=g.nodes.map(p=>p.x),ys=g.nodes.map(p=>p.y);
 const view=n?`${Math.min(...xs)-42} ${Math.min(...ys)-44} ${Math.max(160,Math.max(...xs)-Math.min(...xs)+84)} ${Math.max(150,Math.max(...ys)-Math.min(...ys)+98)}`:'0 0 720 360';
 const field=(id,label,input)=>`<div class="field"><label for="${id}">${label}</label>${input}</div>`;
 const statement=say('07 是替不同頻率乘上一個增益。這裡把增益選成多項式，看看同一個運算怎樣變成「每個節點收集鄰居的值」。','In 07, filtering multiplied each frequency by a gain. Here we choose a polynomial gain and see the same operation become a sum of values from neighboring nodes.');
 $('workspace').innerHTML=`<div class="convolution-intro"><p>${statement}</p><p>${say('本頁沿用你的圖與函數值，固定使用對稱的未正規化矩陣','This page shares your graph and function values and uses the symmetric unnormalized matrix')} ${tex('L_0=D-A')}。${say('因此有正交基底','It therefore has an orthonormal basis')} ${tex(String.raw`L_0=U\Lambda U^{\mathsf T}`)}。</p></div>
 <ol class="convolution-guide"><li>${say('選一個節點，設定它的函數值；也可放一個單點脈衝。','Select a node and edit its value, or place a single-node impulse.')}</li><li>${say('調整混合強度與步數，觀察值最多能傳過幾條邊。','Adjust mixing strength and steps; watch how far values can travel.')}</li><li>${say('對照頻率增益、鄰居貢獻，以及兩種算法的差異。','Compare frequency gains, neighbor contributions, and both calculations.')}</li></ol>
 <section class="panel convolution-editor">${header(say('沿用 07 的函數','The function shared with 07'))}<div class="control-bar">${field('convolution-node',say('觀察與編輯的節點','Node to inspect and edit'),`<select id="convolution-node">${g.nodes.map((_,i)=>`<option value="${i}" ${i===s.selected?'selected':''}>${nodeWord} ${i+1}</option>`).join('')}</select>`)}${field('convolution-value',say('函數值','Function value')+' '+tex('f_i'),`<input id="convolution-value" type="number" min="-2" max="2" step="any" value="${g.nodes[s.selected]?.signal||0}">`)}<button class="small-btn" id="convolution-impulse">${say('選取節點放脈衝','Impulse at selected node')}</button><button class="small-btn" id="convolution-constant">${say('全部設為 1','Set all to 1')}</button><button class="small-btn" id="convolution-undo" ${state.undoHistory?.length?'':'disabled'}>↶ ${say('上一步','Undo')}</button></div>${!n?`<p class="control-explanation">${say('目前沒有節點。請先到','There are no nodes yet. Add some in')} <a href="#playground">01 ${say('圖形實驗場','Graph Playground')}</a>。</p>`:''}</section>
 <div class="convolution-experiment"><section class="panel convolution-controls">${header(say('局部混合規則','Local mixing rule'))}<div class="slider-section"><div class="range-row"><label for="convolution-strength">${say('混合強度','Mixing strength')} ${tex(String.raw`\rho`)}</label><output id="convolution-strength-output"></output></div><input id="convolution-strength" type="range" min="0" max="1" step=".01" value="${s.alphaFraction}"><div class="convolution-alpha" id="convolution-alpha"></div><p>${say('0 保留原值；1 是本圖保持非負混合權重的上限。','0 keeps the input; 1 is the limit that keeps all mixing weights nonnegative on this graph.')}</p></div><div class="slider-section"><div class="range-row"><label for="convolution-steps">${say('混合步數','Mixing steps')} K</label><output id="convolution-steps-output"></output></div><input id="convolution-steps" type="range" min="0" max="3" step="1" value="${s.steps}"><p>${say('每一步只用自己與直接鄰居。0 步不做混合。','Each step uses only the node itself and its direct neighbors. Zero steps leave the input unchanged.')}</p></div><div class="convolution-rule" id="convolution-rule"></div></section>
 <div class="convolution-plots"><section class="panel">${header(say('輸入函數','Input function'),tex('f'))}${svg('',view,'convolution-graph','convolution-input')}<p class="plot-foot" id="convolution-input-foot"></p></section><section class="panel">${header(say('局部混合的結果','Result of local mixing'),tex('y'))}${svg('',view,'convolution-graph','convolution-output')}<p class="plot-foot" id="convolution-output-foot"></p></section><div class="convolution-legend"><span>${say('負值','Negative')}</span><span class="gradient-legend"></span><span>${say('正值','Positive')}</span><span>${say('兩圖使用相同色階；白框為選取節點，金框為 K 步內節點。','Both plots share a color scale. White outline: selected node; gold outline: nodes within K hops.')}</span></div></div></div>
 <div class="convolution-verification" role="status"><span>${say('頻譜計算與局部計算的最大差異','Maximum difference: spectral vs local calculation')}</span><strong id="convolution-error"></strong><span>${say('兩者應僅有數值捨入誤差。','They should agree up to numerical roundoff.')}</span></div>
 <div class="convolution-details"><section class="panel">${header(say('最後一步從哪裡取得數值？','Where does the final step get its values?'))}<div id="convolution-contribution-intro" class="convolution-detail-copy"></div><div class="convolution-table-scroll"><table class="convolution-table"><thead><tr><th>${say('來源','Source')}</th><th>${say('混合權重','Mixing weight')}</th><th>${say('上一步的值','Previous value')}</th><th>${say('貢獻','Contribution')}</th></tr></thead><tbody id="convolution-contributions"></tbody><tfoot><tr><th colspan="3">${say('加總 = 選取節點的輸出','Sum = selected node output')}</th><td id="convolution-contribution-total"></td></tr></tfoot></table></div><p class="convolution-detail-copy">${say('這些是乘在函數值上的混合係數；與作圖時設定的邊權重不同。','These coefficients multiply function values; they are different from the edge weights entered when drawing the graph.')}</p></section>
 <section class="panel">${header(say('同一規則在頻率上長怎樣？','The same rule in the frequency domain'))}<div class="convolution-response-equation" id="convolution-response-equation"></div>${svg('','0 0 540 250','convolution-response','convolution-response')}<p id="convolution-gain-note" class="convolution-detail-copy"></p></section></div>
 <section class="panel convolution-connection">${header(say('從這個濾波器到圖神經網路','From this filter to a graph neural network'))}<div class="convolution-connection-copy"><p>${say('先把已做的事情說清楚：本實驗是固定規則的線性濾波。一般的 K 次多項式可寫成','Our experiment is a linear filter with a fixed rule. A general polynomial of degree K can be written as')}</p><div>${tex(String.raw`g_{\theta}(L_0)f=\sum_{k=0}^{K}\theta_k L_0^k f`,true)}</div><p>${say('每多一個矩陣乘法，資訊最多多走一條邊，所以 K 次多項式只需要 K 步以內的鄰域。若讓係數由資料學習，再加入多維特徵、可學習的矩陣與非線性，就能接到圖神經網路。例如一個簡單的層：','Each multiplication carries information at most one more edge, so a degree-K polynomial only needs the K-hop neighborhood. Learning coefficients from data, adding multiple feature channels, a learned matrix and a nonlinearity leads toward graph neural networks. One simple layer is:')}</p><div>${tex(String.raw`H^{(\ell+1)}=\sigma\!\left(S H^{(\ell)}W^{(\ell)}\right)`,true)}</div><p>${say('H 的每列是某個節點的特徵；S 沿圖混合；W 混合特徵通道；σ 是非線性函數。這裡 σ 是激活函數，不是前面高斯相似度的尺度。經典 GCN 常使用另一種帶自連線的正規化 S。本頁示範的是通往這個想法的線性部分，尚未加入資料標籤、損失函數或訓練。','Each row of H holds one node’s features; S mixes across the graph, W mixes feature channels, and σ is a nonlinear activation. Here σ is not the Gaussian similarity scale from earlier pages. A standard GCN often uses a different normalized S with self-loops. This page demonstrates the linear bridge; it does not introduce labels, a loss function or training.')}</p><p>${say('05 的能量、06 的最小化、07 的頻率基底，在這裡合成同一個觀點：根據圖的結構，決定函數值如何傳遞。整個實驗仍在有限維空間中。','The energy in 05, minimization in 06, and frequency basis in 07 now meet: graph structure determines how function values are mixed. This experiment remains finite-dimensional.')}</p><p class="source-note">${say('延伸閱讀：','Further reading:')} <a href="https://arxiv.org/abs/1606.09375" target="_blank" rel="noopener noreferrer">Defferrard et al. (2016), Localized Spectral Filtering</a> · <a href="https://arxiv.org/abs/1609.02907" target="_blank" rel="noopener noreferrer">Kipf &amp; Welling (2017), Graph Convolutional Networks</a></p></div></section>`;
 function plot(id,values,scale,distances,interactive){
  let body='';
  for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(analysis.A[i][j]>0){const a=g.nodes[i],b=g.nodes[j];body+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#657fa5" stroke-width="1.5" stroke-opacity=".65"/>`;}
  g.nodes.forEach((p,i)=>{const selected=i===s.selected,nearby=distances[i]<=s.steps,stroke=selected?'#f4f7ff':nearby?'#e1bd75':'#294268';body+=`<g transform="translate(${p.x} ${p.y})" ${interactive?`data-convolution-node="${i}" tabindex="0" role="button" aria-label="${nodeWord} ${i+1}, f = ${fmt(values[i],4)}"`:''}><circle r="${selected?14:11}" fill="${color(values[i],scale)}" stroke="${stroke}" stroke-width="${selected?3:2}"/><text text-anchor="middle" y="-22" fill="#d0dcee" font-size="14">${i+1}</text><text text-anchor="middle" y="31" fill="#b4c7e2" font-size="11">${fmt(values[i],2)}</text><title>${nodeWord} ${i+1}: ${fmt(values[i],6)}</title></g>`;});
  if(!n)body=`<text x="360" y="180" text-anchor="middle" fill="#c1cde1">${say('請先在 01 加入節點','Add nodes in 01 to begin')}</text>`;
  $(id).innerHTML=body;
 }
 function response(result){
  const maximum=Math.max(0,...analysis.values),x=lambda=>45+lambda/(maximum||1)*460,y=gain=>112-76*gain;
  let path='';for(let i=0;i<=100;i++){const lambda=maximum*i/100;path+=`${i?'L':'M'}${x(lambda)} ${y((1-result.alpha*lambda)**result.steps)}`;}
  $('convolution-response').innerHTML=`<path d="M45 24V195M45 112H510" stroke="#647e9e" fill="none"/><path d="M45 36H510M45 188H510" stroke="#304c70" stroke-dasharray="4 5" fill="none"/><path d="${path}" stroke="#e2be78" stroke-width="2.5" fill="none"/><text x="18" y="41" fill="#bdcce1" font-size="13">1</text><text x="18" y="117" fill="#bdcce1" font-size="13">0</text><text x="12" y="193" fill="#bdcce1" font-size="13">−1</text><text x="43" y="215" fill="#bdcce1" font-size="13">0</text><text x="508" y="215" text-anchor="end" fill="#bdcce1" font-size="13">${fmt(maximum,2)}</text><text x="506" y="240" fill="#bdcce1" font-size="14">λ</text>${analysis.values.map((lambda,r)=>`<circle cx="${x(lambda)}" cy="${y(result.gains[r])}" r="4" fill="#83a7ff"><title>λ = ${fmt(lambda,5)}, g = ${fmt(result.gains[r],5)}</title></circle>`).join('')}`;
 }
 function update(){
  const f=g.nodes.map(p=>p.signal),result=C.process(analysis,f,s),distances=C.hopDistances(analysis.A,s.selected),scale=Math.max(1,...f.map(Math.abs),...result.output.map(Math.abs));
  plot('convolution-input',f,scale,distances,true);plot('convolution-output',result.output,scale,distances,false);response(result);
  $('convolution-node').value=String(s.selected);if(document.activeElement!==$('convolution-value'))$('convolution-value').value=g.nodes[s.selected]?.signal||0;
  $('convolution-strength-output').textContent=fmt(s.alphaFraction,2);$('convolution-steps-output').textContent=String(s.steps);
  $('convolution-alpha').innerHTML=tex(result.maxDegree>0?String.raw`\alpha=\frac{\rho}{d_{\max}}=\frac{${fmt(s.alphaFraction,2)}}{${fmt(result.maxDegree,3)}}=${fmt(result.alpha,4)}`:String.raw`d_{\max}=0,\quad\alpha=0`);
  $('convolution-rule').innerHTML=tex(String.raw`S=I-\alpha L_0`,true)+tex(String.raw`y=S^{${s.steps}}f`,true);
  $('convolution-error').textContent=result.difference.toExponential(2);
  $('convolution-input-foot').innerHTML=tex('E(f)='+fmt(M.energy(analysis.A,f),5));
  $('convolution-output-foot').innerHTML=tex('E(y)='+fmt(M.energy(analysis.A,result.output),5));
  $('convolution-response-equation').innerHTML=tex(String.raw`g(\lambda)=(1-\alpha\lambda)^{${s.steps}}`,true);
  $('convolution-gain-note').innerHTML=s.steps===0?say('0 步時所有頻率增益都是 1，結果等於輸入。','At zero steps every gain is 1, so the output equals the input.'):say('藍點是本圖的特徵值。增益的絕對值不超過 1，能量不會增加；強度較大時，高頻增益可能為負，表示反轉符號。因此這個規則不一定是單調的低通濾波器。','Blue points mark this graph’s eigenvalues. Gain magnitudes are at most 1, so energy cannot increase. Strong mixing can give negative high-frequency gains, which flip signs; this rule is not necessarily a monotone low-pass filter.');
  const terms=C.contributions(analysis,result,s.selected),last=Math.max(0,s.steps-1);
  $('convolution-contribution-intro').innerHTML=!n?`<p>${say('加入節點後即可查看實際計算。','Add nodes to inspect the calculation.')}</p>`:s.steps===0?`<p>${say('0 步直接保留輸入，沒有鄰居貢獻。','Zero steps keep the input directly; no neighbors contribute.')}</p>${tex(`y_{${s.selected+1}}=f_{${s.selected+1}}`,true)}`:`<p>${say('正在查看節點','Inspecting node')} ${s.selected+1}。${s.steps>1?say(`下表使用第 ${last} 步後的數值，再混合一次得到第 ${s.steps} 步的輸出。`,`The table takes values after step ${last} and mixes them once more to obtain step ${s.steps}.`):say('將自己和每位直接鄰居的值乘上混合權重，再加總。','Multiply the node’s own value and each direct neighbor’s value by its mixing weight, then add.')}</p>${tex(String.raw`x_i^{(${s.steps})}=(1-\alpha d_i)x_i^{(${last})}+\alpha\sum_j w_{ij}x_j^{(${last})}`,true)}`;
  $('convolution-contributions').innerHTML=terms.map(term=>`<tr><th scope="row">${nodeWord} ${term.node+1}${term.self?` <span>${say('自己','self')}</span>`:''}</th><td>${fmt(term.weight,5)}</td><td>${fmt(term.value,5)}</td><td>${fmt(term.contribution,5)}</td></tr>`).join('');
  $('convolution-contribution-total').textContent=n?fmt(result.output[s.selected],6):'—';
  $('convolution-undo').disabled=!state.undoHistory?.length;save();
 }
 const custom=()=>{if(state.spectralSignal)state.spectralSignal.preset='customSignal';};
 function choose(index){s.selected=index;update();}
 $('convolution-node').onchange=e=>choose(+e.target.value);
 let editing=false;$('convolution-value').oninput=e=>{const value=+e.target.value;if(!n||e.target.value===''||!Number.isFinite(value)||value< -2||value>2)return;if(!editing){checkpoint();editing=true;}g.nodes[s.selected].signal=value;custom();update();};
 $('convolution-value').onchange=()=>{editing=false;$('convolution-value').value=g.nodes[s.selected]?.signal||0;};
 $('convolution-impulse').onclick=()=>{if(!n)return;checkpoint();g.nodes.forEach((p,i)=>p.signal=i===s.selected?1:0);custom();update();};
 $('convolution-constant').onclick=()=>{if(!n)return;checkpoint();g.nodes.forEach(p=>p.signal=1);custom();update();};
 $('convolution-strength').oninput=e=>{s.alphaFraction=+e.target.value;update();};
 $('convolution-steps').oninput=e=>{s.steps=+e.target.value;update();};
 $('convolution-undo').onclick=()=>{if(window.LabSession.undo(state)){save();rerender();}};
 $('convolution-input').onclick=e=>{const node=e.target.closest('[data-convolution-node]');if(node)choose(+node.dataset.convolutionNode);};
 $('convolution-input').onkeydown=e=>{if(e.key!=='Enter'&&e.key!==' ')return;const node=e.target.closest('[data-convolution-node]');if(node){e.preventDefault();choose(+node.dataset.convolutionNode);$('convolution-value').focus();}};
 if(!n)for(const id of ['convolution-node','convolution-value','convolution-impulse','convolution-constant','convolution-strength','convolution-steps'])$(id).disabled=true;
 const cards=[
  [say('譜定理：逐個頻率處理','Spectral theorem: act on each frequency'),String.raw`g(L_0)f=U g(\Lambda)U^{\mathsf T}f`,say('先投影到正交特徵向量，再乘增益，最後重建。對重複特徵值使用相同增益，所以結果不依賴那個特徵空間選了哪一組正交基底。','Project onto orthonormal eigenvectors, multiply gains, and reconstruct. Equal eigenvalues receive equal gains, so choosing a different orthonormal basis within a repeated eigenspace gives the same result.')],
  [say('多項式：用矩陣直接算','Polynomial: compute with the matrix'),String.raw`g(\lambda)=(1-\alpha\lambda)^K\ \Longrightarrow\ g(L_0)f=(I-\alpha L_0)^Kf`,say('本頁的兩個算法使用同一個多項式。矩陣算法不需要先求特徵向量；上面的差異數值讓你確認它與頻譜算法一致。','Both calculations use the same polynomial. The matrix calculation does not need eigenvectors; the difference shown above checks agreement with the spectral calculation.')],
  [say('局部性：每次走一條邊','Locality: one edge per step'),String.raw`(Sf)_i=(1-\alpha d_i)f_i+\alpha\sum_j w_{ij}f_j`,say('每個節點保留一部分自己的值，再接收鄰居的值。無邊的孤立節點會保留原值，不同連通分量之間也不會交換訊號。','Each node retains part of its own value and receives values from neighbors. An isolated node keeps its value, and separate connected components do not exchange signals.')]
 ];
 $('math-section').innerHTML=`<div class="math-heading"><span>✧</span><h3>Behind the Spectrum</h3></div><div class="math-cards">${cards.map(([title,equation,body],i)=>`<article class="math-card"><span class="step">0${i+1}</span><h4>${title}</h4><div class="formula">${tex(equation,true)}</div><p>${body}</p></article>`).join('')}</div>`;
 update();
}
window.ConvolutionLabView={render};
})();
