Object.assign(window.LabCopy.zh,{
 foundations:'基礎與參數',sharedGraphNote:'同一張圖，逐步探索。<br>切換模組會保留節點、連線與位置。',definitionsLink:'符號與參數說明 ↗',graph:'作圖區',mathTitle:'Behind the Spectrum',custom:'目前作圖',shared:'目前作圖',geometry:'幾何資料集',dataSource:'分析資料',nextMode:'下一個向量',prevMode:'上一個向量',value:'數值',meaning:'意義',nodeValue:'節點上的值',selectedMode:'目前選取',eigenList:'特徵值列表',eigenHint:'選取 λᵣ，即可查看對應的向量 vᵣ。',zeroMeaning:'零模態',fiedlerMeaning:'Fiedler 模態',otherMode:'第 {r} 個模態',interpretation:'如何解讀這個數字？',storageSaved:'作圖已保留在此瀏覽器',storageUnavailable:'目前頁面會保留作圖；瀏覽器未允許儲存。',sharedGraphLabel:'沿用 00 作圖',foundationIntro:'先設定一張圖，再一步步算出矩陣與光譜。每個符號都有來源，每個數值都對應到你畫的圖。',playgroundIntro:'沿用你的圖，觀察連線如何變成矩陣、特徵值與特徵向量。首次使用可從「00 基礎與參數」開始。',fiedlerIntro:'沿用同一張圖，觀察第二小特徵值與對應向量。改變一條邊，看看連通關係與分割如何回應。',clusteringIntro:'先選擇分析目前作圖或幾何資料集，再比較座標分群與光譜分群。',meshIntro:'將特徵向量看成每個節點上的一個數值，探索目前作圖或 3D 網格的平滑模態。',stepGraph:'圖與權重',stepA:'鄰接矩陣 A',stepD:'度數矩陣 D',stepL:'Laplacian L',stepEigen:'特徵值與向量',youSet:'你設定的量',weDerive:'由圖計算的量',stepGraphBody:'節點代表物件，連線表示兩個物件有關係。邊的權重 wᵢⱼ 表示關係的強度；本實驗只使用無向、非負權重圖。拖動節點只改變畫面位置。',stepABody:'A 是 n × n 的表格：第 i 列、第 j 欄記錄節點 i 與 j 的連線權重。沒有連線就填 0。無向圖有 Aᵢⱼ = Aⱼᵢ；這裡不允許節點連到自己，所以對角線為 0。',stepDBody:'節點 i 的加權度數 dᵢ，就是 A 的第 i 列加總。把每個 dᵢ 放在 D 的對角線，其餘位置填 0。當所有邊權重都是 1，度數才等於連線條數。',stepLBody:'先從 L₀ = D − A 開始：對角線是自己的加權度數，非對角線是連線權重的負值。它比較「自己的值」與「鄰居的值」。正規化版本再用度數調整尺度。',stepEigenBody:'對向量 v，Lv 是矩陣乘法的結果。若乘完後方向不變、只放大 λ 倍，就有 Lv = λv。λ 稱為特徵值，v 稱為特徵向量；兩者由 L 解出，不是手動設定的參數。',currentCalculation:'用目前這張圖計算',nodeI:'節點 i／矩陣列',nodeJ:'節點 j／矩陣欄',currentEntry:'目前選取的元素',weightDefinition:'這條邊的權重由你輸入；沒有連線時 Aᵢⱼ = 0。',degreeDefinition:'加總同一列，就得到這個節點的加權度數。',lapEntryDefinition:'將 D 與 A 的對應元素相減，就得到 L₀ 的這一格。',normalizedEntryDefinition:'在 L₀ 的元素上，依選取的正規化方式除以度數。',eigenEntryDefinition:'兩邊是同一個節點分量的計算結果；極小差異來自數值四捨五入。',graphSymbols:'V：節點集合；E：連線集合；n = |V|：節點數。',nonnegative:'wᵢⱼ ≥ 0。權重為 0 的邊不參與連通性計算。',noNodesLesson:'作圖區目前沒有節點。使用「加節點」工具開始，或載入範例。',zeroDegreeLesson:'這是孤立點，度數為 0。正規化時本實驗把它的列／行設成 0，以避免除以 0。',eigenDefinition:'r 表示排序後第幾個模態；vᵣ(i) 是這個向量在節點 i 上的數值。',unitNorm:'向量採 ‖vᵣ‖₂ = 1 的尺度。整體正負號可以相反，仍是同一個模態。',learnParameters:'參數由誰決定？',learnParametersIntro:'只有「你設定」的量可以調整。矩陣、特徵值與特徵向量會隨圖重新計算。',symbol:'符號',origin:'來源',definition:'定義',yourChoice:'你設定',calculated:'由圖計算',defaultsTitle:'共用設定',newEdgeWeight:'新連線預設權重',newWeightHelp:'新增連線時套用；既有邊的權重不會被一起改動。',typeHelp:'所有模組共用此選擇。先用未正規化理解 D − A，再比較度數正規化。',lapUnnormHelp:'L₀ = D − A。保留權重原來的尺度。',lapSymHelp:'Lsym = D⁻¹ᐟ²L₀D⁻¹ᐟ²。對稱矩陣，同時調整兩端節點的度數。',lapRwHelp:'Lrw = D⁻¹L₀。逐列除以度數；一般不對稱，與隨機漫步有關。',parameterNode:'n：節點數',parameterNodeDef:'數一數作圖區中的節點；矩陣因此有 n 列、n 欄。',parameterWeight:'wᵢⱼ：邊權重',parameterWeightDef:'你對連線指定的強度；預設 1。',parameterA:'A：鄰接矩陣',parameterADef:'把各對節點的權重填成表格。',parameterD:'dᵢ 與 D：加權度數',parameterDDef:'dᵢ = Σⱼ Aᵢⱼ；D 將各個 dᵢ 放在對角線。',parameterL:'L：Laplacian',parameterLDef:'由 A、D 與選擇的正規化方式得到。',parameterEigen:'λᵣ、vᵣ：特徵值／向量',parameterEigenDef:'解 Lvᵣ = λᵣvᵣ，將 λ 由小到大排序。',parameterR:'r：模態序號',parameterRDef:'選擇查看哪一個已計算的特徵向量；不會改變圖。',parameterThreshold:'t：分割閾值',parameterThresholdDef:'用 v₂(i) < t 與 v₂(i) ≥ t 把節點分成兩側。',parameterK:'k：分群數',parameterKDef:'希望光譜分群輸出幾個群；不等於近鄰數。',parameterNeighbors:'q：近鄰數',parameterNeighborsDef:'kNN 建圖時，每個資料點選幾個鄰居。此處用 q 避免與分群數 k 混淆。',parameterSigma:'σ：高斯尺度',parameterSigmaDef:'在 exp(−距離² / 2σ²) 中控制相似度衰減速度；σ 越大，相同距離通常有越大權重。',parameterEpsilon:'ε：連線距離門檻',parameterEpsilonDef:'ε 鄰域模式中，距離小於 ε 才建立連線。',parameterSeed:'seed：隨機種子',parameterSeedDef:'固定產生範例資料與 K-Means 初始化時的隨機序列，方便重現。',geometrySettings:'幾何建圖設定',geometrySettingsHelp:'這些參數只在「03 → 幾何資料集」建圖時生效，不會偷偷改動你手畫的連線。',chooseEdge:'觀察哪一條邊',edgeWeightLabel:'這條邊的權重',edgeWeightHelp:'調整這條已存在的邊；只有確實連接兩個部分的邊才稱為橋。',noEdges:'目前沒有可調整的連線。請先在作圖區加上連線。',vectorExplanation:'每一列對應一個節點。數值為 vᵣ(i)；中線為 0，左側是負值，右側是正值。',coordExplanation:'把同一個 vᵣ(i) 放在水平數線上；垂直錯開只為避免點重疊。',matrixHelp:'點一格可查看計算；矩陣依節點數調整大小，較大矩陣可捲動查看。',emptyMatrix:'尚無節點，因此矩陣為 0 × 0。',definitionZero:'零特徵值的個數，等於圖中彼此不相通的部分數。',definitionFiedler:'對連通圖且 λ₂ 單重時，v₂ 是最平滑的非平凡方向。',definitionOther:'數字越大的模態序號對應排序較後的特徵值；不要把序號當作節點編號。',sharedClusterNote:'使用手畫連線的 A 做光譜分群。左側 K-Means 使用畫面座標作對照，拖動排版會改變左圖的分群，手畫光譜分群不受影響。',sharedMeshNote:'目前作圖的圖模態。使用相同節點與連線，顏色代表 vᵣ(i)；這張圖沒有三角面。',sharedSmallCluster:'目前節點少於設定群數，實際群數已限制為節點數。',emptyShared:'目前沒有節點。請到 00 作圖後再分析。',foundationContinue:'前往 01 觀察光譜 →',eigenvalueShort:'特徵值 λ',definitionShort:'這個模態代表什麼',calcZero:'此特徵值在容差範圍內為 0。',persistHint:'切換模組、語言或重新整理都會保留作圖。'
});
Object.assign(window.LabCopy.en,{
 foundations:'Foundations & Parameters',sharedGraphNote:'One graph, explored step by step.<br>Nodes, edges, and positions stay with you between modules.',definitionsLink:'Symbols & parameters ↗',graph:'Drawing area',mathTitle:'Behind the Spectrum',custom:'Current drawing',shared:'Current drawing',geometry:'Geometric dataset',dataSource:'Analysis source',nextMode:'Next eigenvector',prevMode:'Previous eigenvector',value:'Value',meaning:'Meaning',nodeValue:'Value at the node',selectedMode:'Selected',eigenList:'Eigenvalue list',eigenHint:'Select λᵣ to inspect its corresponding eigenvector vᵣ.',zeroMeaning:'Zero mode',fiedlerMeaning:'Fiedler mode',otherMode:'Mode {r}',interpretation:'How should I read this number?',storageSaved:'Drawing saved in this browser',storageUnavailable:'Drawing stays in this page; browser storage is unavailable.',sharedGraphLabel:'Shared drawing from 00',foundationIntro:'Define a graph, then derive its matrices and spectrum one step at a time. Every symbol has a source; every value comes from your drawing.',playgroundIntro:'Use your graph to see how connections become matrices, eigenvalues, and eigenvectors. New to the notation? Start with 00 Foundations & Parameters.',fiedlerIntro:'Keep the same graph and examine its second-smallest eigenvalue and corresponding vector. Change one edge to explore connectivity and partitioning.',clusteringIntro:'Choose your current drawing or a geometric dataset, then compare coordinate-based and spectral clustering.',meshIntro:'Read an eigenvector as one value per node. Explore smooth modes on your drawing or a 3D mesh.',stepGraph:'Graph & weights',stepA:'Adjacency A',stepD:'Degree D',stepL:'Laplacian L',stepEigen:'Eigenpairs',youSet:'What you choose',weDerive:'What the graph determines',stepGraphBody:'A node represents an object; an edge represents a relationship. Its weight wᵢⱼ specifies the relationship’s strength. This lab uses undirected graphs with nonnegative weights. Dragging nodes only changes the layout.',stepABody:'A is an n × n table. Row i, column j records the weight between nodes i and j; no edge means 0. An undirected graph has Aᵢⱼ = Aⱼᵢ. Self connections are excluded, so the diagonal is 0.',stepDBody:'Node i’s weighted degree dᵢ is the sum of row i of A. Place these degrees on D’s diagonal and fill the other entries with 0. Degree equals the number of edges only when every weight is 1.',stepLBody:'Start with L₀ = D − A. The diagonal contains weighted degrees; off-diagonal entries are negative edge weights. This compares a node’s value with its neighbors’ values. Normalized versions rescale using degrees.',stepEigenBody:'Lv is matrix multiplication applied to a vector v. If it only scales that vector by λ, then Lv = λv. λ is an eigenvalue and v is an eigenvector. They are solved from L, not manually specified parameters.',currentCalculation:'Calculate it on your graph',nodeI:'Node i / matrix row',nodeJ:'Node j / matrix column',currentEntry:'Selected entry',weightDefinition:'You choose this edge’s weight. Without an edge, Aᵢⱼ = 0.',degreeDefinition:'Adding one adjacency row gives this node’s weighted degree.',lapEntryDefinition:'Subtract the corresponding entry of A from D to obtain this entry of L₀.',normalizedEntryDefinition:'Rescale this entry of L₀ by the degrees required by the selected normalization.',eigenEntryDefinition:'Both sides evaluate the same node component. Tiny differences come from numerical rounding.',graphSymbols:'V: node set. E: edge set. n = |V|: number of nodes.',nonnegative:'wᵢⱼ ≥ 0. Zero-weight edges do not contribute to connectivity.',noNodesLesson:'The drawing is empty. Use Add node or load an example to begin.',zeroDegreeLesson:'This node is isolated: its degree is 0. This lab sets its normalized row and column to 0 to avoid division by zero.',eigenDefinition:'r selects a mode in sorted order. vᵣ(i) is that vector’s value at node i.',unitNorm:'Vectors use the scale ‖vᵣ‖₂ = 1. Reversing every sign gives the same mode.',learnParameters:'Who determines each parameter?',learnParametersIntro:'Only values marked “You choose” are inputs. Matrices, eigenvalues, and eigenvectors are recalculated from the graph.',symbol:'Symbol',origin:'Source',definition:'Definition',yourChoice:'You choose',calculated:'Calculated',defaultsTitle:'Shared settings',newEdgeWeight:'Default weight for new edges',newWeightHelp:'Applies to newly created edges. Existing weights stay unchanged.',typeHelp:'All modules share this choice. Begin with D − A before comparing degree normalization.',lapUnnormHelp:'L₀ = D − A. Retains the original scale of the edge weights.',lapSymHelp:'Lsym = D⁻¹ᐟ²L₀D⁻¹ᐟ². Symmetric; rescales by degrees at both endpoints.',lapRwHelp:'Lrw = D⁻¹L₀. Divides each row by its degree; generally nonsymmetric and related to random walks.',parameterNode:'n: number of nodes',parameterNodeDef:'Count the nodes in the drawing. Each matrix has n rows and n columns.',parameterWeight:'wᵢⱼ: edge weight',parameterWeightDef:'The relationship strength you assign to an edge; default 1.',parameterA:'A: adjacency matrix',parameterADef:'Arrange the pairwise edge weights in a table.',parameterD:'dᵢ and D: weighted degrees',parameterDDef:'dᵢ = Σⱼ Aᵢⱼ. D places these degrees on its diagonal.',parameterL:'L: Laplacian',parameterLDef:'Determined by A, D, and the chosen normalization.',parameterEigen:'λᵣ and vᵣ: eigenpair',parameterEigenDef:'Solve Lvᵣ = λᵣvᵣ and sort the eigenvalues in ascending order.',parameterR:'r: mode index',parameterRDef:'Choose which computed eigenvector to inspect. This does not edit the graph.',parameterThreshold:'t: partition threshold',parameterThresholdDef:'Split nodes using v₂(i) < t and v₂(i) ≥ t.',parameterK:'k: cluster count',parameterKDef:'How many clusters to request; this differs from the neighbor count.',parameterNeighbors:'q: neighbor count',parameterNeighborsDef:'How many neighbors each point chooses for kNN. We use q to distinguish it from cluster count k.',parameterSigma:'σ: Gaussian scale',parameterSigmaDef:'Controls decay in exp(−distance² / 2σ²). A larger σ generally gives a greater weight at the same distance.',parameterEpsilon:'ε: distance threshold',parameterEpsilonDef:'In ε-neighborhood mode, points are connected only when their distance is below ε.',parameterSeed:'seed: random seed',parameterSeedDef:'Fixes the random sequence for dataset generation and K-Means initialization for reproducibility.',geometrySettings:'Geometric graph settings',geometrySettingsHelp:'These settings apply to 03 → Geometric dataset. They do not modify your manually drawn edges.',chooseEdge:'Edge to examine',edgeWeightLabel:'Weight of this edge',edgeWeightHelp:'Adjust an existing edge. An edge is a bridge only when removing it separates parts of the graph.',noEdges:'There are no edges to adjust. Add a connection in the drawing area.',vectorExplanation:'One row per node. The number is vᵣ(i); the center is zero, negatives extend left, and positives extend right.',coordExplanation:'The same vᵣ(i) values on a horizontal number line. Vertical offsets only prevent overlap.',matrixHelp:'Select a cell to inspect its calculation. Cells scale with node count; larger matrices can be scrolled.',emptyMatrix:'No nodes: the matrix is 0 × 0.',definitionZero:'The number of zero eigenvalues equals the number of mutually disconnected parts of the graph.',definitionFiedler:'For a connected graph with a simple λ₂, v₂ gives the smoothest nontrivial direction.',definitionOther:'The mode index follows eigenvalue order. It is not a node number.',sharedClusterNote:'Spectral clustering uses your drawn adjacency A. The left K-Means uses display coordinates as a comparison: moving the layout affects that comparison, but not spectral clustering on the drawn edges.',sharedMeshNote:'Modes of your current drawing. The same nodes and edges are used, with color showing vᵣ(i). This graph has no triangle faces.',sharedSmallCluster:'There are fewer nodes than requested clusters; the effective count is limited to the number of nodes.',emptyShared:'There are no nodes. Draw a graph in 00 before analyzing it.',foundationContinue:'Continue to 01: inspect the spectrum →',eigenvalueShort:'Eigenvalue λ',definitionShort:'What does this mode mean?',calcZero:'This eigenvalue is zero within numerical tolerance.',persistHint:'Your drawing survives module changes, language changes, and page reloads.'
});

Object.assign(window.LabCopy.zh,{
  "foundationIntro": "00 是這個實驗室的起點：先放置節點、建立連線與設定權重，再依序理解鄰接矩陣 A、加權度數 D、Laplacian L，以及特徵值與特徵向量。右側每一步都代入目前作圖的數值，說清楚哪些量由你設定、哪些量由圖計算。下方可調整共用參數；完成後，同一張圖會帶到 01–06 繼續觀察。",
  "undo": "上一步",
  "drawingMode": "作圖模式",
  "manual": "手動權重圖",
  "coordinate": "座標平面 · 高斯權重",
  "coordinateDrag": "拖動點會改變距離與權重",
  "coordinateHelp": "座標一格為 1 單位。只需選擇連線，權重由 wᵢⱼ = exp(−‖xᵢ − xⱼ‖² / 2σ²) 計算；未連線仍為 0。拖動節點會即時更新權重、矩陣與光譜。建議 σ 取已選連線的非零長度中位數；無連線時用最近鄰距離。",
  "manualHelp": "連線權重由你設定。拖動節點只改變排版；切換座標模式，距離才會影響權重。",
  "autoWeight": "依距離自動計算；到 01 調整座標或 σ。",
  "recommended": "建議值",
  "datasetScale": "依 03 目前幾何資料估計",
  "sigmaRecommendationHelp": "各點最近非重合鄰居距離的中位數。這是起始尺度，仍需依連通分量與分群結果調整。",
  "applySigma": "套用建議 σ",
  "applyLocalGraph": "套用局部建圖：4 近鄰＋建議 σ",
  "thresholdHelp": "t 是切開 v₂ 數值的門檻：v₂(i) < t 為藍組，v₂(i) ≥ t 為金組。預設 t = 0，依正負號分組；調整 t 只改變著色，不改變圖或特徵值。",
  "recomputed": "已重新計算",
  "partitionUnchanged": "分組維持相同；數值已更新",
  "partitionChanged": "分組已改變",
  "resultReady": "結果已更新",
  "broadSigmaWarning": "目前 σ 超過建議尺度的 3 倍，全連接高斯圖會保留較強的遠距連線，可能把同心圓切成左右兩側。試著套用建議 σ 或局部近鄰圖，再比較結果。分群由連線與權重決定，不會依資料集名稱指定答案。",
  "stepGraphBody": "節點代表物件，連線表示兩個物件有關係。邊的權重 wᵢⱼ 表示關係的強度；本實驗使用無向、非負權重圖。手動模式由你指定權重；座標模式會依距離自動計算。",
  "weightDefinition": "手動模式的權重由你輸入；座標模式由高斯相似度計算。沒有連線時 Aᵢⱼ = 0。",
  "sharedClusterNote": "光譜分群使用目前作圖的鄰接矩陣 A；左側 K-Means 使用節點座標作對照。手動權重模式中，拖動只影響左圖；座標模式中，距離會更新權重，因此兩種分群都可能改變。",
  "mathGraphP3": "手動權重圖的排版不會改變矩陣與光譜。座標模式會依距離更新權重，因此移動節點也會改變光譜。",
  "obsMesh": "選擇模態序號，觀察顏色如何從平滑變化轉成更密集的振盪。這裡的頻率指圖上的變化程度，而非時間頻率。"
});

Object.assign(window.LabCopy.en,{
  "foundationIntro": "Start in 00: place nodes, connect them, and assign weights. Then derive adjacency A, weighted degrees D, Laplacian L, and its eigenpairs. Each step on the right substitutes values from your drawing and distinguishes your inputs from calculated quantities. Configure shared parameters below, then carry the same graph into modules 01–06.",
  "undo": "Undo",
  "drawingMode": "Drawing mode",
  "manual": "Manual weights",
  "coordinate": "Coordinate plane · Gaussian weights",
  "coordinateDrag": "Moving points changes distances and weights",
  "coordinateHelp": "One grid interval is 1 unit. Choose the edges; wᵢⱼ = exp(−‖xᵢ − xⱼ‖² / 2σ²) determines their weights. Unconnected pairs stay at 0. Dragging updates weights, matrices, and spectrum. Suggested σ is the median positive edge length, or nearest-neighbor distance when no edges exist.",
  "manualHelp": "You assign the edge weights. Dragging changes layout; switch to coordinate mode to derive weights from distance.",
  "autoWeight": "Computed from distance; adjust coordinates or σ in 01.",
  "recommended": "Suggested",
  "datasetScale": "Estimated from the current geometric data in 03",
  "sigmaRecommendationHelp": "Median distance to each point’s nearest distinct neighbor. A starting scale: inspect components and clusters, then adjust.",
  "applySigma": "Apply suggested σ",
  "applyLocalGraph": "Use local graph: 4 neighbors + suggested σ",
  "thresholdHelp": "t is the cutoff for v₂ values: v₂(i) < t is blue; v₂(i) ≥ t is gold. The default t = 0 splits by sign. Changing t recolors the partition without changing the graph or eigenvalues.",
  "recomputed": "Recomputed",
  "partitionUnchanged": "Same partition; numerical values updated",
  "partitionChanged": "Partition changed",
  "resultReady": "Result updated",
  "broadSigmaWarning": "σ exceeds 3 times the suggested scale. A full Gaussian graph retains strong long-range links and may split concentric circles into sides. Try suggested σ or a local neighbor graph. Results follow edges and weights, not dataset names.",
  "stepGraphBody": "Nodes represent objects; edges represent relationships. Weight wᵢⱼ measures their strength. This lab uses undirected, nonnegative graphs. Manual mode uses assigned weights; coordinate mode derives them from distance.",
  "weightDefinition": "Weights are assigned in manual mode and derived from Gaussian similarity in coordinate mode. No connection means Aᵢⱼ = 0.",
  "sharedClusterNote": "Spectral clustering uses the current adjacency A; left-side K-Means uses node coordinates. In manual mode, moving nodes only affects the left comparison. In coordinate mode, distances update weights, so both partitions may change.",
  "mathGraphP3": "Layout does not affect a manually weighted graph’s spectrum. In coordinate mode, moving nodes updates distance-based weights and can change the spectrum.",
  "obsMesh": "Select a mode to see smooth variation become denser oscillation. Frequency here measures variation across the graph, not temporal frequency."
});

Object.assign(window.LabCopy.zh,{
  "fourier": "圖傅立葉轉換",
  "filtering": "圖訊號濾波",
  "fourierIntro": "把每個節點上的數值看成訊號，分解成不同光譜模態，再用選定的模態數重建。這裡沿用你在 00–04 建立的圖，訊號也會帶到 06。",
  "filteringIntro": "沿用 05 的圖與訊號，改變各頻率的保留比例，觀察熱擴散低通、高通與理想低通如何影響節點數值。",
  "signalInput": "共用圖訊號",
  "signalPreset": "訊號範例",
  "signalNode": "編輯哪個節點",
  "signalValue": "節點訊號 f(i)",
  "impulseSignal": "單點脈衝",
  "constantSignal": "全部相同",
  "alternatingSignal": "依編號交錯正負",
  "noiseSignal": "固定種子雜訊",
  "customSignal": "自訂訊號",
  "signalHelp": "訊號是附在節點上的數值，與連線權重不同。點選左圖的節點或使用下拉選單，修改 f(i) 即時重算。05、06 共用訊號；原圖的節點位置、連線與權重都沿用。",
  "filterSettings": "濾波器設定",
  "reconstructionSettings": "重建設定",
  "filterKind": "濾波器",
  "heat": "熱擴散低通",
  "highpass": "高通：原訊號減低通",
  "ideal": "理想低通",
  "cutoff": "截止特徵值 λc",
  "diffusionTime": "擴散時間 τ",
  "gainHelp": "縱軸為保留比例 g：1 代表完整保留，0 代表移除。藍點是目前圖的特徵值。熱擴散時間越長，高頻抑制越強；高通則保留被低通移除的部分。",
  "retainedModes": "保留模態數",
  "reconstructionHelp": "依特徵值由小到大保留前 m 個模態。m = 0 輸出零訊號，m = n 完整重建；中間的選擇可觀察近似結果與誤差。",
  "useAllModes": "保留全部模態",
  "inputSignal": "原始訊號",
  "filteredSignal": "濾波後訊號",
  "reconstructedSignal": "重建訊號",
  "sameSignalScale": "兩圖共用相同色階尺度",
  "fourierCoefficients": "逐模態係數",
  "coefficientHelp": "每一列是一個模態。係數正負決定該模態的方向，大小表示參與程度；頻率由特徵值判讀，並非由係數大小決定。能量占比依目前 Laplacian 的內積計算。",
  "mode": "模態 r",
  "modalEnergy": "原始能量占比",
  "frequencyEnergy": "光譜變化能量",
  "maxSignalError": "最大逐點差異",
  "retainedEnergy": "輸出／原始訊號能量",
  "fullReconstructionError": "完整重建誤差",
  "modeTieHelp": "目前截斷位置落在重複特徵值內；選取部分基底的重建會受基底選擇影響。若要對整個重複頻率一致處理，可在 06 使用理想低通。",
  "weightedFourierHelp": "隨機漫步矩陣一般不對稱，這裡使用加權內積做投影：D* 的對角為加權度數，孤立節點取 1。係數採對偶基底，能量也採相同權重，因此保留全部模態仍能重建原訊號。",
  "orthogonalFourierHelp": "未正規化與對稱正規化矩陣都有正交單位特徵向量，因此係數是向量內積；係數平方和等於訊號平方和。光譜變化能量則依特徵值加權，使用目前選取的 Laplacian。",
  "filterTransform": "先轉到光譜座標",
  "filterTransformHelp": "先沿用 05 的投影方式，把每個節點的訊號轉成各模態係數。",
  "filterMultiply": "逐個頻率調整",
  "filterMultiplyHelp": "濾波器將每個係數乘上該頻率的保留比例。相同特徵值使用相同增益，避免依任意基底選擇而改變結果。",
  "filterReconstruct": "轉回節點訊號",
  "filterReconstructHelp": "把調整後的模態相加，就得到右圖的訊號。熱擴散在 τ = 0 保留原訊號；高通在 τ = 0 輸出零。",
  "fourierBasis": "以圖的模態作基底",
  "fourierBasisHelp": "圖決定特徵向量與特徵值。較小特徵值對應較平滑的模式；較大特徵值代表較高的圖頻率。這裡的頻率不是時間頻率。",
  "fourierProjection": "訊號投影成係數",
  "fourierReconstruction": "把模態加回來",
  "fourierReconstructionHelp": "每個係數乘上其特徵向量，再逐項相加。全部 n 個模態形成完整基底；少取幾個模態可觀察平滑近似。"
});

Object.assign(window.LabCopy.en,{
  "fourier": "Graph Fourier Transform",
  "filtering": "Graph Signal Filtering",
  "fourierIntro": "Treat one value per node as a signal. Decompose it into spectral modes, then reconstruct it with a chosen number of modes. Reuse your graph from 00–04 and carry the same signal into 06.",
  "filteringIntro": "Reuse the graph and signal from 05. Change the gain at each graph frequency and compare heat diffusion, high-pass, and ideal low-pass filtering.",
  "signalInput": "Shared graph signal",
  "signalPreset": "Signal example",
  "signalNode": "Node to edit",
  "signalValue": "Signal value f(i)",
  "impulseSignal": "Single-node impulse",
  "constantSignal": "Constant signal",
  "alternatingSignal": "Alternating node indices",
  "noiseSignal": "Seeded noise",
  "customSignal": "Custom signal",
  "signalHelp": "A signal is a value on each node, distinct from edge weights. Select a node in the left plot or dropdown and edit f(i) to update the result. Modules 05–06 share this signal and retain the graph’s positions, edges, and weights.",
  "filterSettings": "Filter settings",
  "reconstructionSettings": "Reconstruction settings",
  "filterKind": "Filter",
  "heat": "Heat diffusion / low-pass",
  "highpass": "High-pass: original minus low-pass",
  "ideal": "Ideal low-pass",
  "cutoff": "Cutoff eigenvalue λc",
  "diffusionTime": "Diffusion time τ",
  "gainHelp": "Vertical gain g is 1 for full retention and 0 for removal. Blue dots mark the current graph’s eigenvalues. Longer diffusion suppresses high frequencies more strongly; high-pass keeps the removed part.",
  "retainedModes": "Retained modes",
  "reconstructionHelp": "Keep the first m modes in ascending eigenvalue order. m = 0 gives zero; m = n fully reconstructs the signal. Intermediate choices show the approximation and error.",
  "useAllModes": "Keep all modes",
  "inputSignal": "Input signal",
  "filteredSignal": "Filtered signal",
  "reconstructedSignal": "Reconstructed signal",
  "sameSignalScale": "Both plots use the same color scale",
  "fourierCoefficients": "Coefficients by mode",
  "coefficientHelp": "Each row is one mode. A coefficient’s sign and magnitude set its contribution; eigenvalues determine frequency. Energy fractions use the inner product for the selected Laplacian.",
  "mode": "Mode r",
  "modalEnergy": "Input energy share",
  "frequencyEnergy": "Spectral variation energy",
  "maxSignalError": "Maximum node difference",
  "retainedEnergy": "Output / input signal energy",
  "fullReconstructionError": "Full reconstruction error",
  "modeTieHelp": "This truncation splits a repeated eigenspace, so the partial reconstruction depends on the chosen basis. Use ideal low-pass in 06 to treat a repeated frequency consistently.",
  "weightedFourierHelp": "The random-walk matrix is generally nonsymmetric. Projection uses a weighted inner product: D* contains degrees, with 1 for isolated nodes. Dual-basis coefficients and energy use the same metric, so all modes still reconstruct the input.",
  "orthogonalFourierHelp": "Unnormalized and symmetric normalized Laplacians have orthonormal eigenvectors. Coefficients are inner products and their squared sum equals the signal’s squared norm. Spectral variation energy additionally weights by eigenvalues of the selected Laplacian.",
  "filterTransform": "Transform to spectral coordinates",
  "filterTransformHelp": "Project the node signal onto the same spectral basis used in 05.",
  "filterMultiply": "Adjust each frequency",
  "filterMultiplyHelp": "Multiply each coefficient by its frequency gain. Equal eigenvalues receive equal gains, avoiding dependence on an arbitrary basis within a repeated eigenspace.",
  "filterReconstruct": "Return to node values",
  "filterReconstructHelp": "Sum the adjusted modes to obtain the right plot. At τ = 0, heat diffusion preserves the input and high-pass returns zero.",
  "fourierBasis": "Use graph modes as a basis",
  "fourierBasisHelp": "The graph determines its eigenvectors and eigenvalues. Smaller eigenvalues describe smoother modes; larger ones represent higher graph frequencies, not temporal frequencies.",
  "fourierProjection": "Project the signal to coefficients",
  "fourierReconstruction": "Sum the modes back together",
  "fourierReconstructionHelp": "Multiply each eigenvector by its coefficient and add the results. All n modes form a complete basis; fewer modes give an approximation using lower frequencies."
});
