/* Page-level learning goals, observation prompts, terminology, and course recap. */
(function(){
'use strict';
const zh={
 foundations:{see:['從你畫的節點與連線，依序得到 A、D、L 與特徵對。','分清楚哪些數值由你輸入，哪些數值由圖的結構計算。'],focus:['先從步驟 1 開始，再依序前進；右側公式會代入目前作圖的真實數值。','改一條邊的權重，觀察矩陣與特徵值如何連動。'],terms:[['圖（graph）','由節點集合 V 與邊集合 E 組成；節點代表物件，邊代表兩個物件有關係。'],['權重 wᵢⱼ','邊 i—j 的強度。本實驗使用非負權重；數值越大表示連結越強。'],['鄰接矩陣 A','用表格記錄哪些節點相連；Aᵢⱼ 就是邊 i—j 的權重，沒有邊時為 0。'],['Laplacian L','由度數與鄰接矩陣組成的矩陣，用來衡量相鄰節點之間的差異。'],['特徵對','若 Lv=λv，v 是特徵向量、λ 是特徵值；L 作用後只改變 v 的尺度。']]},
 playground:{see:['畫出或載入一張圖，直接查看 A、D、L、特徵值與特徵向量。','在座標模式中，以節點距離和高斯相似度自動決定已選連線的權重。'],focus:['手動模式只改位置時，矩陣與光譜不變；座標模式移動節點時，距離會改變權重。','比較未正規化、對稱正規化與隨機漫步 Laplacian。'],terms:[['度數 dᵢ','與節點 i 相連的所有邊權重總和，不只是邊的條數。'],['光譜（spectrum）','一個矩陣全部特徵值的集合；本網站按由小到大排列。'],['高斯相似度','用距離產生權重：距離越近，權重越接近 1；尺度 σ 決定衰減速度。'],['正規化','用節點度數調整尺度，減少高、低度數節點直接比較造成的偏差。']]},
 fiedler:{see:['調整任意一條邊的權重，觀察第二特徵值與第二特徵向量。','移動閾值 t，把連續的 Fiedler 數值轉成兩組節點。'],focus:['把橋接邊變弱，觀察 λ₂ 是否下降，以及向量在哪條邊兩側改變符號。','連通圖與不連通圖的零特徵值數量有何差別。'],terms:[['Fiedler 向量','未正規化 Laplacian 的第二個特徵向量 v₂；它是排除常數方向後最平滑的單位向量。'],['代數連通度 λ₂','連通圖的第二小特徵值；越接近 0，通常表示圖存在較弱的連接。'],['瓶頸（bottleneck）','連接兩個內部緊密群組的少量或低權重邊。'],['閾值 t','把 v₂(i) 與 t 比較：小於 t 的節點進一組，其餘進另一組；t 是切分位置。']]},
 clustering:{see:['把幾何點轉成相似度圖，再比較原座標 K-Means 與光譜分群。','觀察建圖方法、σ、近鄰數與 Laplacian 如何改變結果。'],focus:['同心圓應比較內圈與外圈是否分開，而不是只看顏色名稱。','先查看建議 σ；過大的 σ 會讓遠近點看起來太相似。'],terms:[['相似度圖','把資料點當節點，依距離或近鄰關係建立加權邊。'],['kNN 圖','每個點連到 k 個最近鄰，再把關係對稱化。'],['光譜嵌入','用 Laplacian 的低階特徵向量，替每個節點建立新的座標。'],['K-Means','反覆分配最近中心並更新中心的分群方法；群號本身沒有固定意義。'],['σ（尺度）','高斯權重的距離尺度；它不是標準答案，必須配合資料間距。'],['放寬（relaxation）','先允許原本只能選群別的離散標記取連續實數，解較容易的問題，再把結果轉回群組。']]},
 mesh:{see:['在目前作圖、規則網格或 Bunny 上查看不同特徵模態。','旋轉與縮放 3D 模型，比較低階與高階模態的空間變化。'],focus:['低特徵值模態通常較平緩，高特徵值模態通常在相鄰節點間變化較快。','圖 Laplacian 模態是離散近似，不等同於任意曲面的精確連續解。'],terms:[['網格（mesh）','用頂點、邊與三角形近似表面的離散資料。'],['模態（mode）','一個特徵向量在所有節點上的數值圖樣。'],['特徵函數','連續問題中的 eigenfunction；在有限圖上對應特徵向量。'],['圖頻率','以特徵值衡量沿著邊的變化程度；不是時間訊號每秒振動幾次。']]},
 smoothness:{see:['把向量重新讀成「每個節點各有一個數值」的函數。','逐邊查看差異平方如何加成 Dirichlet 能量。'],focus:['比較平緩、正負交替與常數函數：相鄰值越接近，能量越小。','注意每條無向邊在表格只計算一次。'],terms:[['圖上的函數 f','就是一個 n 維向量；fᵢ 是節點 i 的數值，寫成 f:V→ℝ 只是強調輸入是節點。'],['函數空間','所有可能函數的集合；有限 n 節點時就是熟悉的 ℝⁿ。'],['泛函（functional）','輸入整個向量／函數，輸出一個數。此處 E[f] 是 ℝⁿ→ℝ 的二次式。'],['Dirichlet 能量','所有邊的 wᵢⱼ(fᵢ−fⱼ)² 之和，用一個數衡量函數沿圖的總變化。名稱來自連續理論；本頁只需線性代數。'],['平滑（smooth）','指相連節點的函數值接近，不是畫面上的折線看起來圓滑。']]},
 variational:{see:['從隨機向量開始，反覆降低能量，同時維持平均為 0、長度為 1。','看最平滑的非定值函數如何收斂到 Fiedler 特徵空間。'],focus:['每走一步，能量應下降，而平均值與向量長度應維持限制。','弱橋接圖的解會在橋的兩側形成不同符號。'],terms:[['變分問題','在一整組允許的向量／函數中，尋找讓某個泛函最小者；有限圖上就是有約束的最佳化。'],['Rayleigh 商',String.raw`@@\dfrac{f^{\mathsf T}Lf}{f^{\mathsf T}f}@@；分母除去向量長度造成的尺度，因此把向量放大不會改變比較結果。`],['約束（constraint）','解必須遵守的條件；本頁要求平均為 0 且長度為 1。'],['正交 f⊥1','f 與全 1 向量內積為 0，等價於所有分量總和為 0。'],['特徵空間','同一特徵值對應的所有特徵向量集合；若 λ₂ 重複，最小解不是唯一一條向量。']]},
 fourier:{see:['把節點訊號分解成 Laplacian 特徵向量的係數，再重建原訊號。','保留低頻或套用濾波器，觀察節點數值如何變平滑或突出變化。'],focus:['全部模態能重建原訊號；減少模態後，比較誤差與保留能量。','特徵值決定圖頻率，係數大小只表示該模態在目前訊號中有多少。'],terms:[['圖訊號','每個節點上的一個數值，與 Chapter V 的圖函數是同一種數學物件。'],['基底（basis）','一組可以組合出所有向量的方向；特徵向量提供依平滑程度排序的基底。'],['傅立葉係數','訊號在每個特徵向量方向上的座標，記作 f̂ᵣ。'],['低通濾波','保留低特徵值模態、削弱高特徵值模態，使沿邊快速變化的部分減少。'],['熱擴散','增益 e⁻ᵗˡ；時間 τ 越大，高頻衰減越多。']]},
 convolution:{see:['用譜分解與逐步鄰居混合計算同一個濾波器，核對兩者誤差。','調整混合強度與步數，查看資訊最多傳到幾跳外。'],focus:['選一個節點，讀出「自己＋鄰居」對下一步數值的實際貢獻。','把 K 提高到 8–12，觀察同一連通分量內的值逐漸接近，再區分固定濾波與真正的 GNN。'],terms:[['譜濾波器','讓每個特徵模態乘上依特徵值決定的增益 g(λ)。'],['Laplacian 多項式','由 I、L、L²…組成的矩陣函數；可以用重複矩陣乘法計算。'],['局部性（locality）','K 次多項式的輸出只依賴最多 K 條邊內的節點。'],['圖卷積','依圖的連線，把本節點與鄰居的特徵加權混合；圖上沒有固定左右方向可滑動的濾鏡。'],['訊息傳遞／GNN','節點反覆收集鄰居特徵；GNN 通常再加入可學習權重與非線性，本頁不做模型訓練。'],['過度平滑（over-smoothing）','重複低通或訊息傳遞太多次，使同一連通分量內的節點表示越來越相似，原本可區分的資訊因此減少。']]}
};
const en={
 foundations:{see:['Derive A, D, L, and eigenpairs from the nodes and edges you draw.','Separate values you enter from values computed from graph structure.'],focus:['Begin at Step 1 and proceed in order; worked formulas use the current drawing.','Change one edge weight and watch matrices and eigenvalues respond.'],terms:[['Graph','A vertex set V and edge set E. Vertices represent objects; edges represent relationships.'],['Weight wᵢⱼ','Strength of edge i—j. This lab uses nonnegative weights.'],['Adjacency matrix A','A table of connections: Aᵢⱼ is the edge weight, or 0 when no edge exists.'],['Laplacian L','A matrix built from degrees and adjacency that measures differences across adjacent vertices.'],['Eigenpair','In Lv=λv, v is an eigenvector and λ its eigenvalue; L changes only the scale of v.']]},
 playground:{see:['Draw or load a graph and inspect A, D, L, eigenvalues, and eigenvectors.','In coordinate mode, turn selected edge distances into Gaussian weights.'],focus:['Moving nodes in manual mode leaves the spectrum unchanged; coordinate mode changes distances and weights.','Compare the three Laplacian definitions.'],terms:[['Degree dᵢ','Sum of weights incident to vertex i, not merely the edge count.'],['Spectrum','The complete set of matrix eigenvalues, ordered from small to large here.'],['Gaussian similarity','A distance-based weight; nearer points receive weights closer to 1, controlled by σ.'],['Normalization','Degree-based rescaling used to compare vertices of different degrees.']]},
 fiedler:{see:['Adjust any edge and observe the second eigenvalue and eigenvector.','Move threshold t to turn continuous Fiedler values into two groups.'],focus:['Weaken a bridge and watch λ₂ fall and signs change across the bottleneck.','Compare zero-eigenvalue counts for connected and disconnected graphs.'],terms:[['Fiedler vector','The second eigenvector v₂ of the unnormalized Laplacian: the smoothest unit vector after excluding constants.'],['Algebraic connectivity λ₂','The second-smallest eigenvalue; values near 0 often indicate a weak connection.'],['Bottleneck','A small set of low-weight edges joining internally dense groups.'],['Threshold t','Vertices with v₂(i)<t enter one group and the rest the other; t is the cut position.']]},
 clustering:{see:['Turn points into a similarity graph and compare coordinate-space K-Means with spectral clustering.','See how graph construction, σ, neighbors, and Laplacian alter the result.'],focus:['For concentric circles, check inner-versus-outer membership rather than color names.','Start from suggested σ; an overly broad σ makes far points too similar.'],terms:[['Similarity graph','A weighted graph built from distances or neighbor relations between data points.'],['kNN graph','Connect every point to k nearest neighbors, then symmetrize the relation.'],['Spectral embedding','New vertex coordinates built from low Laplacian eigenvectors.'],['K-Means','Alternates nearest-center assignment and center updates; cluster numbers have no fixed meaning.'],['Scale σ','Distance scale of Gaussian weights; it must match the dataset spacing.'],['Relaxation','Allow discrete group labels to take continuous real values, solve the easier problem, then convert the result back to groups.']]},
 mesh:{see:['Inspect modes on the current drawing, regular meshes, or the Bunny.','Rotate and zoom 3D models and compare low and high modes.'],focus:['Low-eigenvalue modes are usually smoother; high modes change faster across edges.','Graph modes are discrete approximations, not automatically exact surface eigenfunctions.'],terms:[['Mesh','Discrete vertices, edges, and triangles approximating a surface.'],['Mode','The value pattern of one eigenvector over all vertices.'],['Eigenfunction','The continuous analogue of an eigenvector.'],['Graph frequency','Variation across edges measured by eigenvalues, not oscillations per second.']]},
 smoothness:{see:['Read a vector as one value attached to every vertex.','Inspect how squared differences on individual edges add to Dirichlet energy.'],focus:['Compare smooth, alternating, and constant functions.','Each undirected edge is counted once in the table.'],terms:[['Graph function f','Simply an n-vector. Writing f:V→ℝ emphasizes that the input is a vertex.'],['Function space','The set of all possible functions; with n vertices it is the familiar ℝⁿ.'],['Functional','Takes a whole vector/function and returns one scalar. Here E[f] is a quadratic map ℝⁿ→ℝ.'],['Dirichlet energy','The sum of wᵢⱼ(fᵢ−fⱼ)² over edges, measuring total variation. Only linear algebra is needed here.'],['Smooth','Adjacent vertices have similar values; it does not mean the drawn polyline merely looks rounded.']]},
 variational:{see:['Start with a random vector and reduce energy while preserving zero mean and unit length.','Watch the smoothest nonconstant function converge to the Fiedler eigenspace.'],focus:['Energy should decrease while both constraints stay satisfied.','A weak bridge produces opposite signs on its two sides.'],terms:[['Variational problem','Search over allowed vectors/functions for one minimizing a functional; on a finite graph this is constrained optimization.'],['Rayleigh quotient',String.raw`@@\dfrac{f^{\mathsf T}Lf}{f^{\mathsf T}f}@@; the denominator removes arbitrary amplitude scaling, so enlarging the vector does not change the comparison.`],['Constraint','A condition every candidate must satisfy: zero mean and unit length here.'],['Orthogonal f⊥1','The inner product with the all-ones vector is zero, so entries sum to zero.'],['Eigenspace','All eigenvectors sharing one eigenvalue; repeated λ₂ gives multiple minimizing directions.']]},
 fourier:{see:['Decompose a vertex signal into Laplacian eigenvector coefficients and reconstruct it.','Retain low modes or apply filters and observe smoothing or highlighted changes.'],focus:['All modes reconstruct exactly; with fewer modes, compare error and retained energy.','Eigenvalues set frequency; coefficient size only records how much of that mode is present.'],terms:[['Graph signal','One scalar per vertex—the same mathematical object as the graph function in Chapter V.'],['Basis','Directions whose combinations produce every vector; eigenvectors form a smoothness-ordered basis.'],['Fourier coefficient','Coordinate of the signal along one eigenvector, written f̂ᵣ.'],['Low-pass filter','Keeps low-eigenvalue modes and suppresses rapid variation across edges.'],['Heat diffusion','Gain e⁻ᵗˡ; larger τ damps high frequencies more strongly.']]},
 convolution:{see:['Compute one filter spectrally and by repeated neighbor mixing, then compare errors.','Change strength and steps to see how far information travels.'],focus:['Select a node and read the actual self-plus-neighbor contributions.','Raise K to 8–12 and watch values within a component become alike, then separate fixed filtering from a learned GNN.'],terms:[['Spectral filter','Multiplies each eigenmode by a gain g(λ).'],['Laplacian polynomial','A matrix function built from I, L, L², etc., computable by repeated matrix products.'],['Locality','A degree-K polynomial depends on vertices at most K edges away.'],['Graph convolution','Mixes features using graph edges; there is no fixed left-to-right sliding kernel.'],['Message passing / GNN','Vertices repeatedly collect neighbor features; a GNN usually adds learned weights and nonlinearities. No model is trained here.'],['Over-smoothing','Too many low-pass or message-passing steps make vertex representations within a component increasingly alike, erasing distinctions.']]}
};
const stories={
 zh:{
  foundations:['我們從一個很普通的困難開始：物件彼此有關係，但線性代數還無法直接計算這些關係。','怎麼把節點與連線依序變成矩陣？Laplacian 又為什麼能描述一張圖？','畫一張小圖，沿著 G → A → D → L → (λ, v) 前進，逐項核對每個數字從哪裡來。','有了 L 與光譜，下一個問題是：改一條邊時，哪些數值真的會跟著改？Chapter I 會讓你動手測。'],
  playground:['Prologue 已把一張圖翻成 A、D、L 與特徵對；現在要確認這套翻譯究竟保留了哪些結構。','光譜看得到連線與權重的哪些變化？節點畫在螢幕上的位置是否也算圖的結構？','新增或刪除一條邊、改變權重，再比較手動模式與座標模式下的矩陣和光譜。','你會注意到零附近與第二小特徵值特別敏感。Chapter II 接著問：它能不能指出圖最脆弱的地方？'],
  fiedler:['Chapter I 顯示光譜會隨連線改變，但一串特徵值還沒有直接告訴我們弱連接在哪裡。','一個特徵向量能不能同時指出瓶頸，並替節點提供一條可切分的座標軸？','把橋接邊逐漸變弱，追蹤 λ₂、v₂ 與閾值 t；比較斷開前後的零特徵值數量。','若一個低階特徵向量能形成兩組，多個低階特徵向量能否處理更多、更彎曲的群組？Chapter III 會回答。'],
  clustering:['Chapter II 把 v₂ 當成一維座標切成兩側；資料分群需要把這個想法推廣到多個座標。','為什麼「群內連得緊、群間連得弱」的切割問題，最後會變成 Laplacian 特徵向量與 K-Means？','先由距離建立相似度圖，再用低階特徵向量建立新座標；比較原座標與光譜座標中的 K-Means。','分群把特徵向量當成座標。Chapter IV 接著換個角度問：把它畫回整張圖或曲面時，它其實是什麼樣的模態？'],
  mesh:['Chapter III 把每個特徵向量的分量當作節點座標；同一組數字也可以看成離散空間上的函數值。','低特徵值模態為什麼看起來平緩，而高特徵值模態看起來振盪得更快？','在圖、網格與 Bunny 上由低到高切換模態，觀察相鄰頂點的顏色差異如何增加。','「看起來平滑」還不夠精確。Chapter V 會把相鄰差異加總，得到可以比較的能量。'],
  smoothness:['Chapter IV 讓我們看見低階模態較平滑；現在要把視覺直覺變成一個可計算、可比較的數字。','一個 n 維向量既然是節點上的函數，要怎麼衡量它沿著圖變化了多少？','調整各節點的 f(i)，逐邊計算加權差平方，再核對總和等於二次型 fᵀL₀f。','有了能量之後，自然會問：排除不帶變化的常數解，哪個函數的能量最低？Chapter VI 會真的去找它。'],
  variational:['Chapter V 定義了 Dirichlet 能量，但只會替已知函數打分數；我們還沒有從所有可能函數中找到最平滑者。','在平均為 0、長度為 1 的限制下，哪個函數使 fᵀL₀f 最小？為什麼答案又回到特徵向量？','從隨機向量開始做約束下降，觀察能量降低，並核對最後落在 λ₂ 的特徵空間。','特徵向量現在有了平滑度順序。Chapter VII 接著問：能否把它們當成 Fourier 基底來描述任何圖訊號？'],
  fourier:['Chapter VI 說明 Laplacian 特徵向量是依平滑程度排列的方向；一組正交方向也正是一組可用來換座標的基底。','任何節點訊號能否拆成低頻與高頻模態，再選擇保留、削弱或移除哪些部分？','把 f 投影成 f̂，先用全部模態重建，再減少模態或套用低通、高通與熱擴散。','譜公式需要先看見整組特徵向量。Chapter VIII 會問：同一個濾波能否直接由節點和鄰居局部算出來？'],
  convolution:['Chapter VII 已在譜座標中用 g(λ) 調整頻率；最後一步是把全域的譜公式翻回沿著邊進行的局部計算。','為什麼 Laplacian 多項式只需要 K 跳鄰居？它又如何成為圖神經網路訊息傳遞的線性核心？','比較譜計算與逐步鄰居混合；保持預設混合強度並把 K 拉高，觀察高頻消失、同一連通分量內的值逐漸接近。','到這裡，矩陣、平滑、分群、Fourier 與局部傳遞已接成同一條線。留下的問題是如何學習濾波器，並避免過度平滑。']
 },
 en:{
  foundations:['We begin with a simple difficulty: objects are related, but linear algebra cannot yet compute with those relationships.','How do vertices and edges become matrices in sequence, and why can a Laplacian describe a graph?','Draw a small graph and follow G → A → D → L → (λ, v), checking where every number comes from.','Once L and its spectrum exist, ask what really changes when one edge changes. Chapter I lets you test it.'],
  playground:['Prologue translated a graph into A, D, L, and eigenpairs. Now test which parts of the graph that translation preserves.','Which changes in connectivity and weight are visible in the spectrum? Does screen position count as graph structure?','Add or remove an edge, change a weight, and compare matrices and spectra in manual and coordinate modes.','Values near zero, especially the second eigenvalue, will stand out. Chapter II asks whether they locate weak connectivity.'],
  fiedler:['Chapter I showed that the spectrum reacts to edges, but a list of eigenvalues does not yet locate a weak connection.','Can one eigenvector reveal a bottleneck and give every vertex a coordinate that can be cut into two groups?','Weaken a bridge while tracking λ₂, v₂, and threshold t; compare the number of zero eigenvalues before and after disconnection.','If one low eigenvector can form two groups, can several handle more groups with curved geometry? Chapter III answers that.'],
  clustering:['Chapter II used v₂ as one coordinate for two sides. Clustering extends that idea to several coordinates.','Why does the goal “strong links within groups, weak links between groups” lead to Laplacian eigenvectors and K-Means?','Build a similarity graph from distances, use low eigenvectors as new coordinates, then compare K-Means before and after the embedding.','Clustering treats eigenvectors as coordinates. Chapter IV asks what those same vectors look like as modes over a graph or surface.'],
  mesh:['Chapter III used eigenvector entries as vertex coordinates. The same entries can be read as function values over a discrete space.','Why do low-eigenvalue modes look smooth while higher modes oscillate more rapidly?','Move from low to high modes on a graph, mesh, and Bunny; watch differences between neighboring vertex colors grow.','A visual impression of smoothness is not enough. Chapter V turns neighboring differences into a measurable energy.'],
  smoothness:['Chapter IV made low modes look smoother. Now turn that visual intuition into a number that can be computed and compared.','If an n-vector is a function on vertices, how can we measure how much it varies along the graph?','Edit f(i), inspect each weighted squared edge difference, and verify that their sum equals the quadratic form fᵀL₀f.','Once energy is defined, ask which nonconstant function has the least energy. Chapter VI searches for it.'],
  variational:['Chapter V can score a given function with Dirichlet energy, but it has not found the smoothest function among all candidates.','Under zero-mean and unit-length constraints, which f minimizes fᵀL₀f, and why does the answer return to an eigenvector?','Start from a random vector, run constrained descent, and check that it reaches the eigenspace associated with λ₂.','The eigenvectors now have a smoothness order. Chapter VII asks whether they can serve as a Fourier basis for any graph signal.'],
  fourier:['Chapter VI ordered Laplacian eigenvectors by smoothness. Orthogonal directions also form a basis in which a vector can have new coordinates.','Can any vertex signal be split into low and high graph modes, then selectively retained, weakened, or removed?','Project f to f̂, reconstruct with all modes, then use fewer modes or low-pass, high-pass, and heat filters.','The spectral formula uses the full eigenbasis. Chapter VIII asks whether the same filter can be computed locally from neighbors.'],
  convolution:['Chapter VII adjusted frequencies with g(λ). The final step translates that global spectral formula into computation along edges.','Why does a Laplacian polynomial need only K-hop neighbors, and how does this become the linear core of GNN message passing?','Compare spectral evaluation with repeated neighbor mixing. Keep the default mixing strength, raise K, and watch high frequencies disappear as values within a component become alike.','Matrices, smoothness, clustering, Fourier analysis, and local propagation now form one chain. The open questions are how to learn filters and avoid over-smoothing.']
 }
};
const primers={
 zh:{smoothness:['把「函數」翻回向量','這一頁沒有要求你先學泛函分析。有限圖只有 n 個節點，所以一個圖函數就是線性代數中的 n 維向量。符號 f:V→ℝ 只是在說：「輸入節點編號，輸出該節點的實數值。」',String.raw`f=(f_1,\ldots,f_n)^{\mathsf T}\in\mathbb R^n`,'「泛函」則是把整個向量當輸入、輸出一個數。E[f] 的方括號只是提醒輸入是完整函數；在這裡它就是二次型 fᵀL₀f。Dirichlet 能量這個名稱來自連續理論，本頁實際做的只是把每條邊兩端的差平方後加起來。'],variational:['把「變分」翻回有約束最佳化','變分在這裡不是新的神祕運算，而是：在許多向量中找一個讓能量最小的向量。只最小化 fᵀL₀f 會得到零向量，因此固定長度；常數向量仍有零能量，因此再要求與全 1 向量正交。',String.raw`\min f^{\mathsf T}L_0f\quad\text{s.t.}\quad f^{\mathsf T}\mathbf1=0,\ \lVert f\rVert_2=1`,'這正是線性代數的二次型約束最佳化。Lagrange multiplier 的駐點條件會給出 L₀f=λf；最低的允許解就是第二特徵空間。下方動畫真的沿梯度更新，而不是直接把答案畫出來。'],fourier:['把 Graph Fourier 翻回換基底','你已在線性代數中看過「同一向量可以用不同基底表示」。Chapter VII 只把標準座標換成 Laplacian 特徵向量基底。係數不是新的資料，只是同一訊號在另一組座標下的表示。',String.raw`L=U\Lambda U^{\mathsf T},\qquad \widehat f=U^{\mathsf T}f,\qquad f=U\widehat f`,'Chapter V 告訴我們小特徵值模態較平滑，因此這組座標自然帶有低頻到高頻的順序。濾波只是修改各座標的倍率，再換回節點座標；它與時間傅立葉的概念相似，但頻率由圖的連線決定。'],convolution:['Chapter VII 如何走到 Chapter VIII','Chapter VII 的做法是先求全部特徵向量、在譜座標乘上 g(λ)、再重建。這個寫法清楚，卻看起來像每次都要知道整張圖。若 g 是 λ 的低次多項式，就可以把 Λ 換回 L，直接重複矩陣乘法。',String.raw`g(L_0)f=Ug(\Lambda)U^{\mathsf T}f,\qquad g(\lambda)=(1-\alpha\lambda)^K`,'L₀ 的第 i 列只有節點 i 與它的鄰居可能非零，因此乘一次只收集一跳資訊，乘 K 次最多看到 K 跳。這就是譜濾波與局部圖卷積之間的橋。GNN 再加入多維特徵、可學習權重和非線性；本頁只示範橋接它們的線性部分。']},
 en:{smoothness:['Translate “function” back into a vector','No functional analysis is assumed. A finite graph has n vertices, so a graph function is exactly an n-vector. The notation f:V→ℝ only says: input a vertex, output its scalar value.',String.raw`f=(f_1,\ldots,f_n)^{\mathsf T}\in\mathbb R^n`,'A functional takes the whole vector and returns one number. Here E[f] is simply the quadratic form fᵀL₀f. “Dirichlet energy” comes from continuous theory; this page only sums squared differences across edges.'],variational:['Translate “variation” into constrained optimization','Here variation means searching among vectors for one that minimizes energy. Energy alone gives the zero vector, so length is fixed. Constants still have zero energy, so the all-ones direction is excluded.',String.raw`\min f^{\mathsf T}L_0f\quad\text{s.t.}\quad f^{\mathsf T}\mathbf1=0,\ \lVert f\rVert_2=1`,'This is quadratic constrained optimization from linear algebra. Lagrange stationary conditions give L₀f=λf; the lowest allowed solution is the second eigenspace. The animation performs real gradient updates.'],fourier:['Translate Graph Fourier into a basis change','The same vector can have coordinates in different bases. Chapter VII changes from standard coordinates to the Laplacian eigenvector basis. Coefficients are the same signal in new coordinates.',String.raw`L=U\Lambda U^{\mathsf T},\qquad \widehat f=U^{\mathsf T}f,\qquad f=U\widehat f`,'Chapter V showed that smaller-eigenvalue modes are smoother, giving a low-to-high graph-frequency order. Filtering rescales these coordinates and transforms back. Frequency is determined by graph connections.'],convolution:['How Chapter VII leads to Chapter VIII','Chapter VII finds all eigenvectors, multiplies spectral coordinates by g(λ), and reconstructs. If g is a low-degree polynomial in λ, replace Λ by L and use repeated matrix multiplication instead.',String.raw`g(L_0)f=Ug(\Lambda)U^{\mathsf T}f,\qquad g(\lambda)=(1-\alpha\lambda)^K`,'Row i of L₀ only contains vertex i and its neighbors. One multiplication gathers one-hop information; K products reach at most K hops. This connects spectral filtering to local graph convolution. GNNs then add features, learned weights, and nonlinearities; this page demonstrates only the linear bridge.']}
};
primers.zh.clustering=['為什麼分群會變成特徵值問題？','我們原本想把節點分組，使群內連線強、群間切斷的連線弱。若直接要求每個節點只能選某一群，這是很難搜尋的離散最佳化。先允許分組標記取連續實數，就得到 Laplacian 二次型的放寬問題。',String.raw`\min_{x\perp\mathbf1,\ \lVert x\rVert_2=1}x^{\mathsf T}L_0x`,'Rayleigh–Ritz 定理告訴我們，最低的允許方向就是低階特徵向量。Chapter II 用一個非定值方向做二分；Chapter III 同時取多個低階方向，把每個節點放進光譜座標，再由 K-Means 恢復離散群組。對稱正規化與隨機漫步版本會改用度數加權的限制。這是原切割問題的 relaxation，不是 Laplacian 自動知道正確標籤。'];
primers.en.clustering=['Why does clustering become an eigenvalue problem?','We want strong links inside groups and weak links across the cut. Requiring every vertex to choose a discrete group makes direct search difficult. Allowing real-valued group coordinates gives a relaxed problem involving the Laplacian quadratic form.',String.raw`\min_{x\perp\mathbf1,\ \lVert x\rVert_2=1}x^{\mathsf T}L_0x`,'Rayleigh–Ritz makes the lowest allowed directions low Laplacian eigenvectors. Chapter II used one nonconstant direction for a bipartition; Chapter III uses several low directions as spectral coordinates, then K-Means returns discrete groups. Symmetric-normalized and random-walk variants use degree-weighted constraints. This is a relaxation of the cut problem, not a claim that the Laplacian knows the labels.'];
function guide(module,lang,tex){
 const copy=(lang==='en'?en:zh)[module],labels=lang==='en'?['What you can see','What to watch','Terms to know']:['這頁可以看到','請特別觀察','先認識這些詞'];if(!copy)return'';
 const rich=value=>window.SpectralCourse.formatChapters(value).replace(/@@(.+?)@@/g,(_,formula)=>tex(formula));
 const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
 const glossary=`<dl>${copy.terms.map(([term,definition])=>`<div><dt>${rich(term)}</dt><dd>${rich(definition)}</dd></div>`).join('')}</dl>`;
 const primer=primers[lang]?.[module];
 const story=stories[lang]?.[module],storyLabels=lang==='en'?['Context','Research question','Experiment','Next question']:['研究脈絡','研究問題','實驗方法','下一個問題'];
 const storyHtml=story?`<div class="module-story" aria-label="${lang==='en'?'Course storyline':'課程故事主線'}"><div class="module-story-grid">${story.map((body,i)=>`<article class="module-story-step${i===1?' current':''}"><span>${storyLabels[i]}</span><p>${rich(body)}</p></article>`).join('')}</div></div>`:'';
 return `<section class="module-guide" aria-labelledby="module-guide-title"><div class="module-guide-heading"><span>STORY + GUIDE</span><h3 id="module-guide-title">${lang==='en'?'Follow the main thread':'沿著主線開始實驗'}</h3></div>${storyHtml}<div class="module-guide-grid"><article><h4>${labels[0]}</h4>${list(copy.see)}</article><article><h4>${labels[1]}</h4>${list(copy.focus)}</article><article class="module-glossary"><h4>${labels[2]}</h4>${glossary}</article></div>${primer?`<details class="module-primer"><summary>${primer[0]}</summary><div><p>${rich(primer[1])}</p>${tex(primer[2],true)}<p>${rich(primer[3])}</p></div></details>`:''}</section>`;
}
const recapZh=[['foundations','基礎與參數','把關係依序翻成 A、D、L 與特徵對，建立後面共用的語言。'],['playground','圖形實驗場','改變連線與權重，確認圖的結構如何改變矩陣與光譜。'],['fiedler','Fiedler 與連通性','從 λ₂ 與 v₂ 讀出弱連接和一維二分座標。'],['clustering','光譜分群','把圖切割放寬成低階特徵向量座標，再在其中分群。'],['mesh','特徵函數與網格','把特徵向量看成離散空間上由平滑到振盪的模態。'],['smoothness','函數與平滑性','用逐邊差異定義 Dirichlet 能量，量化「平滑」。'],['variational','變分觀點','最小化能量，解釋 Fiedler 向量為何會從限制條件中出現。'],['fourier','圖傅立葉與濾波','把平滑模態當成基底，分解、修改並重建圖訊號。'],['convolution','圖卷積','把譜多項式改寫成局部傳遞，並看見重複平滑的限制。']];
const recapEn=[['foundations','Foundations & Parameters','Translate relationships into A, D, L, and eigenpairs, establishing the shared language.'],['playground','Graph Playground','Change edges and weights to test how structure changes matrices and spectra.'],['fiedler','Fiedler & Connectivity','Read weak connectivity and a one-dimensional bipartition coordinate from λ₂ and v₂.'],['clustering','Spectral Clustering','Relax graph cuts into low-eigenvector coordinates, then cluster in that space.'],['mesh','Eigenfunctions & Mesh','Read eigenvectors as modes from smooth to oscillatory over a discrete space.'],['smoothness','Functions & Smoothness','Use edgewise differences to define Dirichlet energy and quantify smoothness.'],['variational','Variational View','Minimize energy to explain why the Fiedler vector emerges from constraints.'],['fourier','Graph Fourier & Filtering','Use smooth modes as a basis to decompose, modify, and reconstruct graph signals.'],['convolution','Graph Convolution','Rewrite spectral polynomials as local propagation and expose the limit of repeated smoothing.']];
function summary(module,lang,tex){if(module!=='convolution')return'';const enMode=lang==='en',rows=enMode?recapEn:recapZh;return `<section class="course-summary"><div class="math-heading"><span>✦</span><h3>${enMode?'Course conclusion':'實驗室總結'}</h3></div><p>${enMode?'The course began by asking how linear algebra can compute with relationships. The same graph has now been read as a matrix, a geometry, a function space, and an operator that transports information. The questions and answers from Prologue through Chapter VIII are below.':'整段故事從「怎麼讓線性代數處理關係」開始。同一張圖現在有四種相容的讀法：矩陣、幾何、函數空間，以及傳遞資訊的算子。以下整理 Prologue 到 Chapter VIII 的問題與答案。'}</p><div class="course-recap">${rows.map(([key,title,body])=>`<article><span>${window.SpectralCourse.chapter(key).label}</span><div><h4>${title}</h4><p>${body}</p></div></article>`).join('')}</div><div class="course-final-equation">${tex(String.raw`\text{graph}\to L\to(\lambda_r,v_r)\to E[f]\to\widehat f\to g(L)f\to\text{local message passing}`,true)}</div><p>${enMode?'The central answer is now visible: Laplacian eigenvectors are the graph’s constrained smooth modes. They expose connectivity, provide spectral coordinates, and turn filtering into local propagation when the filter is polynomial. Repeating a low-pass step suppresses high frequencies until vertex representations become alike—over-smoothing. A learned GNN continues from here by learning feature transformations and filters.':'核心答案現在完整了：Laplacian 特徵向量是圖在限制條件下的平滑模態，所以它們能揭露連通性、提供分群座標，也能在濾波器是多項式時把譜運算改寫成局部傳遞。重複低通會一直壓低高頻，直到節點表示變得相似，這就是過度平滑。真正可學習的 GNN 則從這裡繼續加入特徵轉換與學習參數。'}</p></section>`;}
Object.assign(window.SpectralCourse,{guide,summary});
})();
