/* Page-level learning goals, observation prompts, terminology, and course recap. */
(function(){
'use strict';
const zh={
 foundations:{see:['從你畫的節點與連線，依序得到 A、D、L 與特徵對。','分清楚哪些數值由你輸入，哪些數值由圖的結構計算。'],focus:['先從步驟 1 開始，再依序前進；右側公式會代入目前作圖的真實數值。','改一條邊的權重，觀察矩陣與特徵值如何連動。'],terms:[['圖（graph）','由節點集合 V 與邊集合 E 組成；節點代表物件，邊代表兩個物件有關係。'],['權重 wᵢⱼ','邊 i—j 的強度。本實驗使用非負權重；數值越大表示連結越強。'],['鄰接矩陣 A','用表格記錄哪些節點相連；Aᵢⱼ 就是邊 i—j 的權重，沒有邊時為 0。'],['Laplacian L','由度數與鄰接矩陣組成的矩陣，用來衡量相鄰節點之間的差異。'],['特徵對','若 Lv=λv，v 是特徵向量、λ 是特徵值；L 作用後只改變 v 的尺度。']]},
 playground:{see:['畫出或載入一張圖，直接查看 A、D、L、特徵值與特徵向量。','在座標模式中，以節點距離和高斯相似度自動決定已選連線的權重。'],focus:['手動模式只改位置時，矩陣與光譜不變；座標模式移動節點時，距離會改變權重。','比較未正規化、對稱正規化與隨機漫步 Laplacian。'],terms:[['度數 dᵢ','與節點 i 相連的所有邊權重總和，不只是邊的條數。'],['光譜（spectrum）','一個矩陣全部特徵值的集合；本網站按由小到大排列。'],['高斯相似度','用距離產生權重：距離越近，權重越接近 1；尺度 σ 決定衰減速度。'],['正規化','用節點度數調整尺度，減少高、低度數節點直接比較造成的偏差。']]},
 fiedler:{see:['調整任意一條邊的權重，觀察第二特徵值與第二特徵向量。','移動閾值 t，把連續的 Fiedler 數值轉成兩組節點。'],focus:['把橋接邊變弱，觀察 λ₂ 是否下降，以及向量在哪條邊兩側改變符號。','連通圖與不連通圖的零特徵值數量有何差別。'],terms:[['Fiedler 向量','未正規化 Laplacian 的第二個特徵向量 v₂；它是排除常數方向後最平滑的單位向量。'],['代數連通度 λ₂','連通圖的第二小特徵值；越接近 0，通常表示圖存在較弱的連接。'],['瓶頸（bottleneck）','連接兩個內部緊密群組的少量或低權重邊。'],['閾值 t','把 v₂(i) 與 t 比較：小於 t 的節點進一組，其餘進另一組；t 是切分位置。']]},
 clustering:{see:['把幾何點轉成相似度圖，再比較原座標 K-Means 與光譜分群。','觀察建圖方法、σ、近鄰數與 Laplacian 如何改變結果。'],focus:['同心圓應比較內圈與外圈是否分開，而不是只看顏色名稱。','先查看建議 σ；過大的 σ 會讓遠近點看起來太相似。'],terms:[['相似度圖','把資料點當節點，依距離或近鄰關係建立加權邊。'],['kNN 圖','每個點連到 k 個最近鄰，再把關係對稱化。'],['光譜嵌入','用 Laplacian 的低階特徵向量，替每個節點建立新的座標。'],['K-Means','反覆分配最近中心並更新中心的分群方法；群號本身沒有固定意義。'],['σ（尺度）','高斯權重的距離尺度；它不是標準答案，必須配合資料間距。']]},
 mesh:{see:['在目前作圖、規則網格或 Bunny 上查看不同特徵模態。','旋轉與縮放 3D 模型，比較低階與高階模態的空間變化。'],focus:['低特徵值模態通常較平緩，高特徵值模態通常在相鄰節點間變化較快。','圖 Laplacian 模態是離散近似，不等同於任意曲面的精確連續解。'],terms:[['網格（mesh）','用頂點、邊與三角形近似表面的離散資料。'],['模態（mode）','一個特徵向量在所有節點上的數值圖樣。'],['特徵函數','連續問題中的 eigenfunction；在有限圖上對應特徵向量。'],['圖頻率','以特徵值衡量沿著邊的變化程度；不是時間訊號每秒振動幾次。']]},
 smoothness:{see:['把向量重新讀成「每個節點各有一個數值」的函數。','逐邊查看差異平方如何加成 Dirichlet 能量。'],focus:['比較平緩、正負交替與常數函數：相鄰值越接近，能量越小。','注意每條無向邊在表格只計算一次。'],terms:[['圖上的函數 f','就是一個 n 維向量；fᵢ 是節點 i 的數值，寫成 f:V→ℝ 只是強調輸入是節點。'],['函數空間','所有可能函數的集合；有限 n 節點時就是熟悉的 ℝⁿ。'],['泛函（functional）','輸入整個向量／函數，輸出一個數。此處 E[f] 是 ℝⁿ→ℝ 的二次式。'],['Dirichlet 能量','所有邊的 wᵢⱼ(fᵢ−fⱼ)² 之和，用一個數衡量函數沿圖的總變化。名稱來自連續理論；本頁只需線性代數。'],['平滑（smooth）','指相連節點的函數值接近，不是畫面上的折線看起來圓滑。']]},
 variational:{see:['從隨機向量開始，反覆降低能量，同時維持平均為 0、長度為 1。','看最平滑的非定值函數如何收斂到 Fiedler 特徵空間。'],focus:['每走一步，能量應下降，而平均值與向量長度應維持限制。','弱橋接圖的解會在橋的兩側形成不同符號。'],terms:[['變分問題','在一整組允許的向量／函數中，尋找讓某個泛函最小者；有限圖上就是有約束的最佳化。'],['Rayleigh 商',String.raw`@@\dfrac{f^{\mathsf T}Lf}{f^{\mathsf T}f}@@；分母除去向量長度造成的尺度，因此把向量放大不會改變比較結果。`],['約束（constraint）','解必須遵守的條件；本頁要求平均為 0 且長度為 1。'],['正交 f⊥1','f 與全 1 向量內積為 0，等價於所有分量總和為 0。'],['特徵空間','同一特徵值對應的所有特徵向量集合；若 λ₂ 重複，最小解不是唯一一條向量。']]},
 fourier:{see:['把節點訊號分解成 Laplacian 特徵向量的係數，再重建原訊號。','保留低頻或套用濾波器，觀察節點數值如何變平滑或突出變化。'],focus:['全部模態能重建原訊號；減少模態後，比較誤差與保留能量。','特徵值決定圖頻率，係數大小只表示該模態在目前訊號中有多少。'],terms:[['圖訊號','每個節點上的一個數值，與 05 的圖函數是同一種數學物件。'],['基底（basis）','一組可以組合出所有向量的方向；特徵向量提供依平滑程度排序的基底。'],['傅立葉係數','訊號在每個特徵向量方向上的座標，記作 f̂ᵣ。'],['低通濾波','保留低特徵值模態、削弱高特徵值模態，使沿邊快速變化的部分減少。'],['熱擴散','增益 e⁻ᵗˡ；時間 τ 越大，高頻衰減越多。']]},
 convolution:{see:['用譜分解與逐步鄰居混合計算同一個濾波器，核對兩者誤差。','調整混合強度與步數，查看資訊最多傳到幾跳外。'],focus:['選一個節點，讀出「自己＋鄰居」對下一步數值的實際貢獻。','區分固定線性濾波與真正含可學習參數、特徵通道和非線性的 GNN。'],terms:[['譜濾波器','讓每個特徵模態乘上依特徵值決定的增益 g(λ)。'],['Laplacian 多項式','由 I、L、L²…組成的矩陣函數；可以用重複矩陣乘法計算。'],['局部性（locality）','K 次多項式的輸出只依賴最多 K 條邊內的節點。'],['圖卷積','依圖的連線，把本節點與鄰居的特徵加權混合；圖上沒有固定左右方向可滑動的濾鏡。'],['訊息傳遞／GNN','節點反覆收集鄰居特徵；GNN 通常再加入可學習權重與非線性，本頁不做模型訓練。']]}
};
const en={
 foundations:{see:['Derive A, D, L, and eigenpairs from the nodes and edges you draw.','Separate values you enter from values computed from graph structure.'],focus:['Begin at Step 1 and proceed in order; worked formulas use the current drawing.','Change one edge weight and watch matrices and eigenvalues respond.'],terms:[['Graph','A vertex set V and edge set E. Vertices represent objects; edges represent relationships.'],['Weight wᵢⱼ','Strength of edge i—j. This lab uses nonnegative weights.'],['Adjacency matrix A','A table of connections: Aᵢⱼ is the edge weight, or 0 when no edge exists.'],['Laplacian L','A matrix built from degrees and adjacency that measures differences across adjacent vertices.'],['Eigenpair','In Lv=λv, v is an eigenvector and λ its eigenvalue; L changes only the scale of v.']]},
 playground:{see:['Draw or load a graph and inspect A, D, L, eigenvalues, and eigenvectors.','In coordinate mode, turn selected edge distances into Gaussian weights.'],focus:['Moving nodes in manual mode leaves the spectrum unchanged; coordinate mode changes distances and weights.','Compare the three Laplacian definitions.'],terms:[['Degree dᵢ','Sum of weights incident to vertex i, not merely the edge count.'],['Spectrum','The complete set of matrix eigenvalues, ordered from small to large here.'],['Gaussian similarity','A distance-based weight; nearer points receive weights closer to 1, controlled by σ.'],['Normalization','Degree-based rescaling used to compare vertices of different degrees.']]},
 fiedler:{see:['Adjust any edge and observe the second eigenvalue and eigenvector.','Move threshold t to turn continuous Fiedler values into two groups.'],focus:['Weaken a bridge and watch λ₂ fall and signs change across the bottleneck.','Compare zero-eigenvalue counts for connected and disconnected graphs.'],terms:[['Fiedler vector','The second eigenvector v₂ of the unnormalized Laplacian: the smoothest unit vector after excluding constants.'],['Algebraic connectivity λ₂','The second-smallest eigenvalue; values near 0 often indicate a weak connection.'],['Bottleneck','A small set of low-weight edges joining internally dense groups.'],['Threshold t','Vertices with v₂(i)<t enter one group and the rest the other; t is the cut position.']]},
 clustering:{see:['Turn points into a similarity graph and compare coordinate-space K-Means with spectral clustering.','See how graph construction, σ, neighbors, and Laplacian alter the result.'],focus:['For concentric circles, check inner-versus-outer membership rather than color names.','Start from suggested σ; an overly broad σ makes far points too similar.'],terms:[['Similarity graph','A weighted graph built from distances or neighbor relations between data points.'],['kNN graph','Connect every point to k nearest neighbors, then symmetrize the relation.'],['Spectral embedding','New vertex coordinates built from low Laplacian eigenvectors.'],['K-Means','Alternates nearest-center assignment and center updates; cluster numbers have no fixed meaning.'],['Scale σ','Distance scale of Gaussian weights; it must match the dataset spacing.']]},
 mesh:{see:['Inspect modes on the current drawing, regular meshes, or the Bunny.','Rotate and zoom 3D models and compare low and high modes.'],focus:['Low-eigenvalue modes are usually smoother; high modes change faster across edges.','Graph modes are discrete approximations, not automatically exact surface eigenfunctions.'],terms:[['Mesh','Discrete vertices, edges, and triangles approximating a surface.'],['Mode','The value pattern of one eigenvector over all vertices.'],['Eigenfunction','The continuous analogue of an eigenvector.'],['Graph frequency','Variation across edges measured by eigenvalues, not oscillations per second.']]},
 smoothness:{see:['Read a vector as one value attached to every vertex.','Inspect how squared differences on individual edges add to Dirichlet energy.'],focus:['Compare smooth, alternating, and constant functions.','Each undirected edge is counted once in the table.'],terms:[['Graph function f','Simply an n-vector. Writing f:V→ℝ emphasizes that the input is a vertex.'],['Function space','The set of all possible functions; with n vertices it is the familiar ℝⁿ.'],['Functional','Takes a whole vector/function and returns one scalar. Here E[f] is a quadratic map ℝⁿ→ℝ.'],['Dirichlet energy','The sum of wᵢⱼ(fᵢ−fⱼ)² over edges, measuring total variation. Only linear algebra is needed here.'],['Smooth','Adjacent vertices have similar values; it does not mean the drawn polyline merely looks rounded.']]},
 variational:{see:['Start with a random vector and reduce energy while preserving zero mean and unit length.','Watch the smoothest nonconstant function converge to the Fiedler eigenspace.'],focus:['Energy should decrease while both constraints stay satisfied.','A weak bridge produces opposite signs on its two sides.'],terms:[['Variational problem','Search over allowed vectors/functions for one minimizing a functional; on a finite graph this is constrained optimization.'],['Rayleigh quotient',String.raw`@@\dfrac{f^{\mathsf T}Lf}{f^{\mathsf T}f}@@; the denominator removes arbitrary amplitude scaling, so enlarging the vector does not change the comparison.`],['Constraint','A condition every candidate must satisfy: zero mean and unit length here.'],['Orthogonal f⊥1','The inner product with the all-ones vector is zero, so entries sum to zero.'],['Eigenspace','All eigenvectors sharing one eigenvalue; repeated λ₂ gives multiple minimizing directions.']]},
 fourier:{see:['Decompose a vertex signal into Laplacian eigenvector coefficients and reconstruct it.','Retain low modes or apply filters and observe smoothing or highlighted changes.'],focus:['All modes reconstruct exactly; with fewer modes, compare error and retained energy.','Eigenvalues set frequency; coefficient size only records how much of that mode is present.'],terms:[['Graph signal','One scalar per vertex—the same mathematical object as the graph function in 05.'],['Basis','Directions whose combinations produce every vector; eigenvectors form a smoothness-ordered basis.'],['Fourier coefficient','Coordinate of the signal along one eigenvector, written f̂ᵣ.'],['Low-pass filter','Keeps low-eigenvalue modes and suppresses rapid variation across edges.'],['Heat diffusion','Gain e⁻ᵗˡ; larger τ damps high frequencies more strongly.']]},
 convolution:{see:['Compute one filter spectrally and by repeated neighbor mixing, then compare errors.','Change strength and steps to see how far information travels.'],focus:['Select a node and read the actual self-plus-neighbor contributions.','Separate fixed linear filtering from GNNs with learnable weights and nonlinearities.'],terms:[['Spectral filter','Multiplies each eigenmode by a gain g(λ).'],['Laplacian polynomial','A matrix function built from I, L, L², etc., computable by repeated matrix products.'],['Locality','A degree-K polynomial depends on vertices at most K edges away.'],['Graph convolution','Mixes features using graph edges; there is no fixed left-to-right sliding kernel.'],['Message passing / GNN','Vertices repeatedly collect neighbor features; a GNN usually adds learned weights and nonlinearities. No model is trained here.']]}
};
const primers={
 zh:{smoothness:['把「函數」翻回向量','這一頁沒有要求你先學泛函分析。有限圖只有 n 個節點，所以一個圖函數就是線性代數中的 n 維向量。符號 f:V→ℝ 只是在說：「輸入節點編號，輸出該節點的實數值。」',String.raw`f=(f_1,\ldots,f_n)^{\mathsf T}\in\mathbb R^n`,'「泛函」則是把整個向量當輸入、輸出一個數。E[f] 的方括號只是提醒輸入是完整函數；在這裡它就是二次型 fᵀL₀f。Dirichlet 能量這個名稱來自連續理論，本頁實際做的只是把每條邊兩端的差平方後加起來。'],variational:['把「變分」翻回有約束最佳化','變分在這裡不是新的神祕運算，而是：在許多向量中找一個讓能量最小的向量。只最小化 fᵀL₀f 會得到零向量，因此固定長度；常數向量仍有零能量，因此再要求與全 1 向量正交。',String.raw`\min f^{\mathsf T}L_0f\quad\text{s.t.}\quad f^{\mathsf T}\mathbf1=0,\ \lVert f\rVert_2=1`,'這正是線性代數的二次型約束最佳化。Lagrange multiplier 的駐點條件會給出 L₀f=λf；最低的允許解就是第二特徵空間。下方動畫真的沿梯度更新，而不是直接把答案畫出來。'],fourier:['把 Graph Fourier 翻回換基底','你已在線性代數中看過「同一向量可以用不同基底表示」。07 只把標準座標換成 Laplacian 特徵向量基底。係數不是新的資料，只是同一訊號在另一組座標下的表示。',String.raw`L=U\Lambda U^{\mathsf T},\qquad \widehat f=U^{\mathsf T}f,\qquad f=U\widehat f`,'05 告訴我們小特徵值模態較平滑，因此這組座標自然帶有低頻到高頻的順序。濾波只是修改各座標的倍率，再換回節點座標；它與時間傅立葉的概念相似，但頻率由圖的連線決定。'],convolution:['07 如何走到 08','07 的做法是先求全部特徵向量、在譜座標乘上 g(λ)、再重建。這個寫法清楚，卻看起來像每次都要知道整張圖。若 g 是 λ 的低次多項式，就可以把 Λ 換回 L，直接重複矩陣乘法。',String.raw`g(L_0)f=Ug(\Lambda)U^{\mathsf T}f,\qquad g(\lambda)=(1-\alpha\lambda)^K`,'L₀ 的第 i 列只有節點 i 與它的鄰居可能非零，因此乘一次只收集一跳資訊，乘 K 次最多看到 K 跳。這就是譜濾波與局部圖卷積之間的橋。GNN 再加入多維特徵、可學習權重和非線性；本頁只示範橋接它們的線性部分。']},
 en:{smoothness:['Translate “function” back into a vector','No functional analysis is assumed. A finite graph has n vertices, so a graph function is exactly an n-vector. The notation f:V→ℝ only says: input a vertex, output its scalar value.',String.raw`f=(f_1,\ldots,f_n)^{\mathsf T}\in\mathbb R^n`,'A functional takes the whole vector and returns one number. Here E[f] is simply the quadratic form fᵀL₀f. “Dirichlet energy” comes from continuous theory; this page only sums squared differences across edges.'],variational:['Translate “variation” into constrained optimization','Here variation means searching among vectors for one that minimizes energy. Energy alone gives the zero vector, so length is fixed. Constants still have zero energy, so the all-ones direction is excluded.',String.raw`\min f^{\mathsf T}L_0f\quad\text{s.t.}\quad f^{\mathsf T}\mathbf1=0,\ \lVert f\rVert_2=1`,'This is quadratic constrained optimization from linear algebra. Lagrange stationary conditions give L₀f=λf; the lowest allowed solution is the second eigenspace. The animation performs real gradient updates.'],fourier:['Translate Graph Fourier into a basis change','The same vector can have coordinates in different bases. Module 07 changes from standard coordinates to the Laplacian eigenvector basis. Coefficients are the same signal in new coordinates.',String.raw`L=U\Lambda U^{\mathsf T},\qquad \widehat f=U^{\mathsf T}f,\qquad f=U\widehat f`,'Module 05 showed that smaller-eigenvalue modes are smoother, giving a low-to-high graph-frequency order. Filtering rescales these coordinates and transforms back. Frequency is determined by graph connections.'],convolution:['How 07 leads to 08','Module 07 finds all eigenvectors, multiplies spectral coordinates by g(λ), and reconstructs. If g is a low-degree polynomial in λ, replace Λ by L and use repeated matrix multiplication instead.',String.raw`g(L_0)f=Ug(\Lambda)U^{\mathsf T}f,\qquad g(\lambda)=(1-\alpha\lambda)^K`,'Row i of L₀ only contains vertex i and its neighbors. One multiplication gathers one-hop information; K products reach at most K hops. This connects spectral filtering to local graph convolution. GNNs then add features, learned weights, and nonlinearities; this page demonstrates only the linear bridge.']}
};
function guide(module,lang,tex){
 const copy=(lang==='en'?en:zh)[module],labels=lang==='en'?['What you can see','What to watch','Terms to know']:['這頁可以看到','請特別觀察','先認識這些詞'];if(!copy)return'';
 const rich=value=>String(value).replace(/@@(.+?)@@/g,(_,formula)=>tex(formula));
 const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
 const glossary=`<dl>${copy.terms.map(([term,definition])=>`<div><dt>${rich(term)}</dt><dd>${rich(definition)}</dd></div>`).join('')}</dl>`;
 const primer=primers[lang]?.[module];
 return `<section class="module-guide" aria-labelledby="module-guide-title"><div class="module-guide-heading"><span>GUIDE</span><h3 id="module-guide-title">${lang==='en'?'Before you experiment':'開始實驗前'}</h3></div><div class="module-guide-grid"><article><h4>${labels[0]}</h4>${list(copy.see)}</article><article><h4>${labels[1]}</h4>${list(copy.focus)}</article><article class="module-glossary"><h4>${labels[2]}</h4>${glossary}</article></div>${primer?`<details class="module-primer"><summary>${primer[0]}</summary><div><p>${rich(primer[1])}</p>${tex(primer[2],true)}<p>${rich(primer[3])}</p></div></details>`:''}</section>`;
}
const recapZh=[['01','圖形實驗場','把圖轉成 A、D、L 與光譜。'],['02','Fiedler 與連通性','用 λ₂ 與 v₂ 找出弱連接和二分結構。'],['03','光譜分群','先建相似度圖，再到特徵向量座標中分群。'],['04','特徵函數與網格','把特徵向量看成離散空間上的模態。'],['05','函數與平滑性','用逐邊差異定義 Dirichlet 能量。'],['06','變分觀點','從約束最小化推導特徵向量與 Fiedler 向量。'],['07','圖傅立葉與濾波','在按平滑度排序的基底中分解、修改與重建訊號。'],['08','圖卷積','把譜多項式改寫成 K 跳鄰居的局部計算。']];
const recapEn=[['01','Graph Playground','Turn a graph into A, D, L, and a spectrum.'],['02','Fiedler & Connectivity','Use λ₂ and v₂ to expose weak connections and bipartitions.'],['03','Spectral Clustering','Build a similarity graph, then cluster in eigenvector coordinates.'],['04','Eigenfunctions & Mesh','View eigenvectors as modes over a discrete space.'],['05','Functions & Smoothness','Define Dirichlet energy from edgewise differences.'],['06','Variational View','Derive eigenvectors and the Fiedler vector from constrained minimization.'],['07','Graph Fourier & Filtering','Decompose, modify, and reconstruct signals in a smoothness-ordered basis.'],['08','Graph Convolution','Rewrite a spectral polynomial as a local K-hop computation.']];
function summary(module,lang,tex){if(module!=='convolution')return'';const enMode=lang==='en',rows=enMode?recapEn:recapZh;return `<section class="course-summary"><div class="math-heading"><span>✦</span><h3>${enMode?'Course conclusion':'實驗室總結'}</h3></div><p>${enMode?'The same graph has now been read in four compatible ways: as a matrix, a geometry, a function space, and an operator that transports information.':'同一張圖現在有四種相容的讀法：矩陣、幾何、函數空間，以及傳遞資訊的算子。01–08 的關係如下。'}</p><div class="course-recap">${rows.map(([n,title,body])=>`<article><span>${n}</span><div><h4>${title}</h4><p>${body}</p></div></article>`).join('')}</div><div class="course-final-equation">${tex(String.raw`\text{graph}\to L\to(\lambda_r,v_r)\to E[f]\to\widehat f\to g(L)f\to\text{local message passing}`,true)}</div><p>${enMode?'The central answer is now visible: the spectrum encodes graph structure because Laplacian eigenvectors are the constrained smooth modes of that graph. They provide coordinates in which structured variation and filtering become explicit.':'核心答案是：Laplacian 的特徵向量是這張圖在限制條件下最自然的平滑模態，因此光譜能把連通性、分群、函數變化與訊息傳遞放進同一套座標中。08 展示了通往 GNN 的數學橋樑，並沒有宣稱已經訓練模型。'}</p></section>`;}
Object.assign(window.SpectralCourse,{guide,summary});
})();
