(function(){
'use strict';
function render(ctx){
 const {state,M,$,t,tex,fmt,header,select,svg,color,save,checkpoint,rerender}=ctx,S=window.SignalMath,g=state.graph,s=state.spectralSignal,filtering=s.view==='filtering',n=g.nodes.length;
 window.LabSession.refreshWeights(M,state);
 const analysis=M.analyze(g.nodes,g.edges,state.type),fresh=g.nodes.every(p=>!Number.isFinite(p.signal));
 g.nodes.forEach((p,i)=>{if(!Number.isFinite(p.signal))p.signal=fresh&&i===0?1:0;});
 s.selected=Math.min(Math.max(0,s.selected),Math.max(0,n-1));s.modes=Math.min(Math.max(0,s.modes),n);
 const xs=g.nodes.map(p=>p.x),ys=g.nodes.map(p=>p.y),graphView=n?`${Math.min(...xs)-40} ${Math.min(...ys)-45} ${Math.max(160,Math.max(...xs)-Math.min(...xs)+80)} ${Math.max(140,Math.max(...ys)-Math.min(...ys)+90)}`:'0 0 720 360';
 const maxLambda=Math.max(0,...analysis.values),cutoffMax=Math.max(1,maxLambda,s.cutoff);
 const field=(id,label,body)=>`<div class="field"><label for="${id}">${label}</label>${body}</div>`;
 const picker=field('signal-node',t('signalNode'),`<select id="signal-node">${g.nodes.map((_,i)=>`<option value="${i}" ${i===s.selected?'selected':''}>${t('node')} ${i+1}</option>`).join('')}</select>`);
 $('workspace').innerHTML=`<div class="signal-view-tabs" role="group" aria-label="${t('signalViews')}"><button data-signal-view="reconstruction" aria-pressed="${!filtering}">${t('reconstructionView')}</button><button data-signal-view="filtering" aria-pressed="${filtering}">${t('filteringView')}</button></div><p class="signal-task">${t(filtering?'filteringTask':'reconstructionTask')}</p><section class="panel signal-settings">${header(t('signalInput'))}<div class="control-bar">${select('signal-preset','signalPreset',['impulseSignal','constantSignal','alternatingSignal','noiseSignal','customSignal'],s.preset)}${picker}${field('signal-level',t('signalValue'),`<input id="signal-level" type="number" min="-2" max="2" step="any" value="${g.nodes[s.selected]?.signal||0}">`)}${select('signal-laplacian','laplacian',['unnormalized','symmetric','randomwalk'],state.type)}<button class="small-btn" id="signal-undo" ${state.undoHistory?.length?'':'disabled'}>↶ ${t('undo')}</button></div><p class="control-explanation">${t('signalHelp')}</p>${!n?`<p class="lesson-empty">${t('emptyShared')}</p>`:''}</section>
 <div class="signal-experiment"><section class="panel signal-actions">${header(t(filtering?'filterSettings':'reconstructionSettings'))}${filtering?`<div class="control-bar">${select('signal-filter','filterKind',['heat','highpass','ideal'],s.filter)}</div><div class="slider-section"><div class="range-row"><label for="filter-parameter">${t(s.filter==='ideal'?'cutoff':'diffusionTime')}</label><output id="filter-parameter-output"></output></div><input id="filter-parameter" type="range" min="0" max="${s.filter==='ideal'?cutoffMax:10}" step="${s.filter==='ideal'?cutoffMax/1000:.01}" value="${s.filter==='ideal'?s.cutoff:s.tau}"></div><div class="filter-formula" id="filter-formula"></div>${svg('','0 0 540 235','filter-response','filter-response')}<p class="control-explanation">${t('gainHelp')}</p>`:`<div class="slider-section"><div class="range-row"><label for="retained-modes">${t('retainedModes')} m</label><output id="retained-modes-output"></output></div><input id="retained-modes" type="range" min="0" max="${n}" step="1" value="${s.modes}"></div><p class="control-explanation">${t('reconstructionHelp')}</p><button class="secondary-btn" id="all-modes">${t('useAllModes')}</button><div class="signal-metrics" id="signal-metrics"></div><p class="control-explanation" id="truncated-tie"></p>`}</section>
 <div class="signal-comparison"><section class="panel">${header(t('inputSignal'),tex('f'))}${svg('',graphView,'signal-graph','signal-input-plot')}<div class="plot-foot"><span id="signal-input-energy"></span></div></section><section class="panel">${header(t(filtering?'filteredSignal':'reconstructedSignal'),tex(filtering?'y':'f_m'))}${svg('',graphView,'signal-graph','signal-output-plot')}<div class="plot-foot"><span id="signal-output-energy"></span></div></section><div class="signal-color-key"><span>${t('negative')}</span><span class="gradient-legend"></span><span>${t('positive')}</span><span>${t('sameSignalScale')}</span></div></div></div>
 ${filtering?'<div class="signal-metrics filter-metrics" id="signal-metrics"></div>':''}<section class="panel signal-coefficients">${header(t('fourierCoefficients'))}<p class="panel-description">${t('coefficientHelp')}</p><div class="coefficient-scroll"><table class="coefficient-table"><thead><tr><th>${t('mode')}</th><th>${tex(String.raw`\lambda_r`)}</th><th>${tex(String.raw`\hat f_r`)}</th><th>${tex(filtering?String.raw`g(\lambda_r)`:String.raw`r\leq m`)}</th><th>${tex(filtering?String.raw`\hat y_r`:String.raw`\widehat{f_m}_r`)}</th><th>${t('modalEnergy')}</th></tr></thead><tbody id="signal-coefficients"></tbody></table></div></section><p class="control-explanation">${t(state.type==='randomwalk'?'weightedFourierHelp':'orthogonalFourierHelp')}</p>`;
 document.querySelectorAll('[data-signal-view]').forEach(button=>button.onclick=()=>{s.view=button.dataset.signalView;save();rerender();});
 const metric=(name,value)=>`<div><span>${name}</span><strong>${value}</strong></div>`;
 function plot(id,values,scale,interactive){
  let body='';
  for(const e of g.edges){if(e.w<=0)continue;const a=g.nodes[e.a],b=g.nodes[e.b];body+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#5d7da9" stroke-opacity=".65" stroke-width="1.4"/>`;}
  g.nodes.forEach((p,i)=>{const fill=color(values[i],scale);body+=`<g ${interactive?`data-signal-node="${i}" tabindex="0" role="button" aria-label="${t('node')} ${i+1}, f = ${fmt(values[i],4)}"`:''} transform="translate(${p.x} ${p.y})"><circle r="${interactive&&i===s.selected?14:11}" fill="${fill}" stroke="${interactive&&i===s.selected?'#ffffff':'#112647'}" stroke-width="2"/><text y="-21" text-anchor="middle" fill="#c4d4ec" font-size="13">${i+1}</text><title>${t('node')} ${i+1}: ${fmt(values[i],6)}</title></g>`;});
  if(!n)body+=`<text x="360" y="180" text-anchor="middle" fill="#aabfda">${t('emptyShared')}</text>`;
  $(id).innerHTML=body;
 }
 function response(){
  const width=460,height=140,top=30,left=48,x=lambda=>left+lambda/(maxLambda||1)*width,y=value=>top+(1-value)*height;
  let path='';
  if(s.filter==='ideal'){const cut=Math.min(maxLambda,s.cutoff);path=`M${left} ${top}H${x(cut)}${s.cutoff<maxLambda?`V${y(0)}H${x(maxLambda)}`:''}`;}else for(let i=0;i<=100;i++){const lambda=maxLambda*i/100;path+=`${i?'L':'M'}${x(lambda)} ${y(S.gain(lambda,s.filter,s.tau,s.cutoff))}`;}
  $('filter-response').innerHTML=`<path d="M${left} ${top-10}V${y(0)}H${left+width+8}" fill="none" stroke="#577095"/><path d="${path}" fill="none" stroke="#e2bf7e" stroke-width="2"/><text x="18" y="34" fill="#afc4e0" font-size="13">1</text><text x="18" y="174" fill="#afc4e0" font-size="13">0</text><text x="46" y="198" fill="#afc4e0" font-size="13">0</text><text x="508" y="198" text-anchor="end" fill="#afc4e0" font-size="13">${fmt(maxLambda,2)}</text><text x="510" y="218" fill="#afc4e0" font-size="13">λ</text>${analysis.values.map((lambda,r)=>`<circle cx="${x(lambda)}" cy="${y(S.gain(lambda,s.filter,s.tau,s.cutoff))}" r="3.5" fill="#83a7ff"><title>λ${r+1} = ${fmt(lambda,4)}, g = ${fmt(S.gain(lambda,s.filter,s.tau,s.cutoff),4)}</title></circle>`).join('')}`;
 }
 function update(){
  const input=g.nodes.map(p=>p.signal),result=S.process(analysis,input,state.type,{kind:filtering?s.filter:'truncate',modes:s.modes,tau:s.tau,cutoff:s.cutoff}),scale=Math.max(1,...input.map(Math.abs),...result.output.map(Math.abs));
  plot('signal-input-plot',input,scale,true);plot('signal-output-plot',result.output,scale,false);
  if(document.activeElement!==$('signal-level'))$('signal-level').value=g.nodes[s.selected]?.signal||0;$('signal-node').value=String(s.selected);
  $('signal-input-energy').innerHTML=`${t('frequencyEnergy')} ${tex('E_L(f)='+fmt(result.frequencyEnergy,5))}`;
  $('signal-output-energy').innerHTML=`${t('frequencyEnergy')} ${tex(`E_L(${filtering?'y':'f_m'})=${fmt(result.outputFrequencyEnergy,5)}`)}`;
  $('signal-metrics').innerHTML=metric(t('maxSignalError'),fmt(result.error,6))+metric(t('retainedEnergy'),result.energy>1e-15?fmt(100*result.outputEnergy/result.energy,1)+'%':'—')+(!filtering?metric(t('fullReconstructionError'),result.fullError.toExponential(2)):'');
  const peak=Math.max(1e-12,...result.coefficients.map(Math.abs));
  $('signal-coefficients').innerHTML=result.coefficients.map((c,r)=>`<tr class="${result.gains[r]===0?'muted-mode':''}"><th scope="row">${r+1}</th><td>${fmt(analysis.values[r],5)}</td><td><span class="coefficient-number">${fmt(c,5)}</span><span class="coefficient-track"><i style="width:${Math.abs(c)/peak*100}%;background:${c<0?'#81a4ff':'#dfbd7d'}"></i></span></td><td>${filtering?fmt(result.gains[r],4):r<s.modes?'✓':'—'}</td><td>${fmt(result.filteredCoefficients[r],5)}</td><td>${result.energy>1e-15?fmt(100*result.modalEnergy[r]/result.energy,1)+'%':'—'}</td></tr>`).join('');
  if(filtering){$('filter-parameter-output').textContent=fmt(s.filter==='ideal'?s.cutoff:s.tau,3);$('filter-formula').innerHTML=tex(s.filter==='ideal'?String.raw`g(\lambda)=\begin{cases}1,&\lambda\leq\lambda_c\\0,&\lambda>\lambda_c\end{cases}`:s.filter==='highpass'?String.raw`g(\lambda)=1-e^{-\tau\lambda}`:String.raw`g(\lambda)=e^{-\tau\lambda}`,true);response();}
  else{$('retained-modes-output').textContent=`${s.modes} / ${n}`;$('truncated-tie').textContent=s.modes>0&&s.modes<n&&Math.abs(analysis.values[s.modes-1]-analysis.values[s.modes])<analysis.tolerance?t('modeTieHelp'):'';}
  $('signal-undo').disabled=!state.undoHistory?.length;save();
 }
 function preset(kind){if(kind==='customSignal')return;checkpoint();const random=M.rng(s.seed);g.nodes.forEach((p,i)=>p.signal=kind==='impulseSignal'?(i===s.selected?1:0):kind==='constantSignal'?1:kind==='alternatingSignal'?(i%2?-1:1):random()*2-1);update();}
 $('signal-preset').onchange=e=>{s.preset=e.target.value;preset(s.preset);save();};
 $('signal-node').onchange=e=>{s.selected=+e.target.value;update();};
 let editing=false;$('signal-level').oninput=e=>{const value=+e.target.value;if(e.target.value===''||!Number.isFinite(value)||value< -2||value>2||!n)return;if(!editing){checkpoint();editing=true;}g.nodes[s.selected].signal=value;s.preset='customSignal';$('signal-preset').value=s.preset;update();};
 $('signal-level').onchange=()=>{editing=false;$('signal-level').value=g.nodes[s.selected]?.signal||0;};
 $('signal-laplacian').onchange=e=>{window.LabSession.setType(state,e.target.value);save();rerender();};
 $('signal-undo').onclick=()=>{if(window.LabSession.undo(state)){save();rerender();}};
 $('signal-input-plot').onclick=e=>{const node=e.target.closest('[data-signal-node]');if(node){s.selected=+node.dataset.signalNode;update();}};
 $('signal-input-plot').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const node=e.target.closest('[data-signal-node]');if(node){e.preventDefault();s.selected=+node.dataset.signalNode;update();$('signal-level').focus();}}};
 if(filtering){$('signal-filter').onchange=e=>{s.filter=e.target.value;save();rerender();};$('filter-parameter').oninput=e=>{s[s.filter==='ideal'?'cutoff':'tau']=+e.target.value;update();};}
 else{$('retained-modes').oninput=e=>{s.modes=+e.target.value;update();};$('all-modes').onclick=()=>{s.modes=n;$('retained-modes').value=n;update();};}
 if(!n)for(const id of ['signal-node','signal-level','signal-preset','retained-modes','all-modes','filter-parameter'])if($(id))$(id).disabled=true;
 const coeff=state.type==='randomwalk'?String.raw`\hat f_r=\frac{v_r^{\mathsf T}D_*f}{v_r^{\mathsf T}D_*v_r}`:String.raw`\hat f_r=v_r^{\mathsf T}f`;
 const cards=filtering?[[t('filterTransform'),coeff,t('filterTransformHelp')],[t('filterMultiply'),String.raw`\hat y_r=g(\lambda_r)\hat f_r`,t('filterMultiplyHelp')],[t('filterReconstruct'),String.raw`y=\sum_{r=1}^n\hat y_rv_r`,t('filterReconstructHelp')]]:[[t('fourierBasis'),String.raw`L v_r=\lambda_r v_r`,t('fourierBasisHelp')],[t('fourierProjection'),coeff,t(state.type==='randomwalk'?'weightedFourierHelp':'orthogonalFourierHelp')],[t('fourierReconstruction'),String.raw`f_m=\sum_{r=1}^m\hat f_rv_r`,t('fourierReconstructionHelp')]];
 $('math-section').innerHTML=`<div class="spectral-energy-connection"><p>${t(state.type==='unnormalized'?'spectralEnergyLink':'spectralEnergyNormalized')}</p><div>${tex(state.type==='randomwalk'?String.raw`E_L(f)=\sum_{r=1}^n\lambda_r\lvert\hat f_r\rvert^2\lVert v_r\rVert_{D_*}^2`:String.raw`f^{\mathsf T}Lf=\sum_{r=1}^n\lambda_r\lvert\hat f_r\rvert^2`,true)}</div></div><div class="math-heading"><span>✧</span><h3>${t('mathTitle')}</h3></div><div class="math-cards">${cards.map(([title,formula,body],i)=>`<article class="math-card"><span class="step">0${i+1}</span><h4>${title}</h4><div class="formula">${tex(formula,true)}</div><p>${body}</p></article>`).join('')}</div>`;
 update();
}
window.SignalLabView={render};
})();
