(function(){
'use strict';
let dispose=()=>{};
function cleanup(){dispose();dispose=()=>{};}
function render(ctx){
 cleanup();
 const {state,M,$,tex,fmt,header,svg,color,save,rerender}=ctx,V=window.VariationalMath,isDescent=state.module==='variational',en=state.lang==='en',say=(zh,eng)=>en?eng:zh;
 const s=state.variationalLab||(state.variationalLab={smoothSource:'path5',smoothValues:{},descentSource:'bridge6',descentSeed:7,descentValues:[],descentHistory:[],descentGraphKey:'',descentIteration:0});
 s.smoothValues=s.smoothValues||{};
 const sourceKey=isDescent?'descentSource':'smoothSource';
 if(!['path5','bridge6','shared'].includes(s[sourceKey]))s[sourceKey]=isDescent?'bridge6':'path5';
 const source=s[sourceKey];
 if(source==='shared')window.LabSession.refreshWeights(M,state);
 const g=source==='shared'?state.graph:V.teachingGraph(source),n=g.nodes.length,a=M.analyze(g.nodes,g.edges,'unnormalized'),target=V.targetSpace(a);
 const graphKey=JSON.stringify([source,n,a.A]),smoothKey=source==='shared'?'shared':source;
 if(!Array.isArray(s.smoothValues[smoothKey])||s.smoothValues[smoothKey].length!==n)s.smoothValues[smoothKey]=Array.from({length:n},(_,i)=>n<=5?1+.1*i:1+.4*i/(n-1));
 s.smoothValues[smoothKey]=s.smoothValues[smoothKey].map(x=>Number.isFinite(x)?Math.max(-2,Math.min(2,x)):0);
 let running=false,timer=null,active=true;
 dispose=()=>{active=false;running=false;clearTimeout(timer);};
 const sourceSelect=`<div class="field"><label for="variational-source">${say('觀察的圖','Graph to explore')}</label><select id="variational-source">${[['path5',say('教學例：5 節點路徑','Teaching example: 5-node path')],['bridge6',say('教學例：6 節點弱橋接','Teaching example: 6-node weak bridge')],['shared',say('使用目前作圖','Use current drawing')]].map(([v,label])=>`<option value="${v}" ${source===v?'selected':''}>${label}</option>`).join('')}</select></div>`;
 const sourceHelp=source==='shared'?say('讀取 00–02 的圖與邊權重。這裡的函數值另行保存，不會改動原本的作圖。','Uses the graph and edge weights from 00–02. Function values are stored separately from your drawing.'):say('教學例與你的作圖分開保存；可切換成「使用目前作圖」比較。','The teaching example is stored separately; select “Use current drawing” to compare.');
 const nodeText=say('節點','Node'),energyText=say('Dirichlet 能量','Dirichlet energy');
 $('workspace').innerHTML=`<section class="panel variational-source"><div class="control-bar">${sourceSelect}<span class="variational-convention">${tex(String.raw`L_0=D-A`)}</span></div><p class="control-explanation">${sourceHelp} ${say('本節固定使用未正規化 Laplacian，讓常數函數的能量為零。','This section uses the unnormalized Laplacian, whose constant functions have zero energy.')}</p></section>
 <div class="variational-experiment"><section class="panel variational-controls">${header(say(isDescent?'讓平滑函數自己出現':'每個節點給一個函數值',isDescent?'Let a smooth function emerge':'Assign a value to each node'))}${isDescent?descentControls():smoothControls()}</section>
 <section class="panel variational-visual">${header(say('圖上的函數','A function on the graph'),tex(String.raw`f:V\to\mathbb R`))}${svg('','0 0 720 240','variational-graph','variational-graph')}<div class="variational-key"><span>${say('負值','Negative')}</span><span class="gradient-legend"></span><span>${say('正值','Positive')}</span><span>${say('節點旁數字是函數值','Numbers beside nodes are function values')}</span></div>${svg('','0 0 720 200','variational-values','variational-values')}<p class="plot-foot">${say('橫軸是節點編號，縱軸是函數值。折線只用來比較數值；是否相鄰，仍由上方圖的連線決定。','The horizontal axis is node index and the vertical axis is function value. The line compares values; graph edges above determine adjacency.')}</p></section></div>
 ${isDescent?descentBelow():smoothBelow()}`;
 function smoothControls(){return `<p class="control-explanation">${say('向量的第 i 個座標，就是函數在節點 i 的值。拉動滑桿，觀察相鄰值的落差如何增加能量。','Coordinate i of the vector is the function value at node i. Move a slider to see how differences across edges add energy.')}</p><div class="variational-presets"><button class="small-btn" data-function-preset="smooth">${say('平緩','Smooth')}</button><button class="small-btn" data-function-preset="alternating">${say('正負交替','Alternating')}</button><button class="small-btn" data-function-preset="constant">${say('常數','Constant')}</button></div><div class="variational-node-sliders">${g.nodes.map((_,i)=>`<div class="variational-node-row"><label for="function-node-${i}">${tex(`f_{${i+1}}`)}</label><input id="function-node-${i}" type="range" min="-2" max="2" step=".01" value="${s.smoothValues[smoothKey][i]}" aria-label="${nodeText} ${i+1} ${say('函數值','function value')}"><output id="function-node-output-${i}" for="function-node-${i}"></output></div>`).join('')||`<p class="control-explanation">${say('目前沒有節點。可改用教學例，或先到 01 作圖。','There are no nodes. Choose a teaching example or draw a graph in 01.')}</p>`}</div><div class="variational-total"><span>${energyText}</span><strong id="function-total"></strong><p>${say('相鄰節點越接近，能量越小；整體一起加上常數，不會改變能量。','Closer values on adjacent nodes give lower energy. Adding the same constant everywhere leaves energy unchanged.')}</p></div>`;}
 function descentControls(){return `<div class="variational-objective">${tex(String.raw`\min_{\substack{f\perp\mathbf1\\\|f\|_2=1}}f^{\mathsf T}L_0f`,true)}</div><p class="control-explanation">${say('先取隨機函數，扣除平均值並正規化。每一步沿能量下降方向移動，再恢復這兩項限制。','Start with a random function, subtract its mean, and normalize it. Each step reduces energy, then restores both constraints.')}</p><div class="variational-buttons"><button class="secondary-btn" id="descent-step">${say('走一步','One step')}</button><button class="secondary-btn" id="descent-run">${say('連續迭代','Run')}</button><button class="small-btn" id="descent-reset">${say('重來','Reset')}</button><button class="small-btn" id="descent-new">${say('換一組起點','New start')}</button></div><div class="variational-metrics" id="descent-metrics"></div><p class="control-explanation variational-status" id="descent-status" role="status"></p>`;}
 function smoothBelow(){return `<section class="panel variational-edge-panel">${header(say('把能量拆成每一條邊','Account for every edge'))}<div class="variational-identity variational-identity-steps">${tex(String.raw`\begin{aligned}E[f]&=f^{\mathsf T}L_0f=f^{\mathsf T}(D-A)f\\&=\sum_i d_i f_i^2-\sum_{i,j}w_{ij}f_if_j,\qquad d_i=\sum_jw_{ij},\end{aligned}`,true)}${tex(String.raw`\begin{aligned}&=\frac12\sum_{i,j}w_{ij}\bigl(f_i^2-2f_if_j+f_j^2\bigr)\\&=\frac12\sum_{i,j}w_{ij}(f_i-f_j)^2\\&=\sum_{\{i,j\}\in E}w_{ij}(f_i-f_j)^2.\end{aligned}`,true)}</div><p class="panel-description">${say('第一行先代入 L₀ = D − A；再用 dᵢ = ∑ⱼwᵢⱼ，把度數項與鄰接項合併成差的平方。雙重求和會把 i → j 和 j → i 都算一次，所以乘 1/2；最後改成無向邊集合 E 的求和時，每條邊只計一次。圖上的線越粗，代表這條邊貢獻的能量越大。','First substitute L₀ = D − A. Then use dᵢ = ∑ⱼwᵢⱼ to combine the degree and adjacency terms into a squared difference. The double sum counts i → j and j → i, so it needs 1/2; summing over undirected edges E counts each edge once. Thicker edges contribute more energy.')}</p><div class="variational-table-scroll"><table class="variational-table"><thead><tr><th>${say('邊','Edge')}</th><th>${tex('w_{ij}')}</th><th>${tex('f_i-f_j')}</th><th>${tex('w_{ij}(f_i-f_j)^2')}</th></tr></thead><tbody id="function-edge-rows"></tbody></table></div><p class="control-explanation">${say('在 5 節點路徑上，平緩範例的能量是 0.04，正負交替則是 16。這比較的是相鄰差異；若振幅不同，也要用 06 的 Rayleigh 商排除尺度影響。','On the 5-node path, the smooth example has energy 0.04 and the alternating example has energy 16. Energy measures adjacent differences; use the Rayleigh quotient in 06 to remove amplitude scaling.')}</p></section>`;}
 function descentBelow(){return `<section class="panel variational-history-panel">${header(say('看能量隨迭代下降','Watch the energy decrease'))}${svg('','0 0 900 240','variational-history','descent-history')}<p class="panel-description">${say('金線是實際迭代得到的能量，藍色虛線是理論最小值。與最小值的差距和到目標子空間的距離一起判斷是否已經收斂。','Gold is the energy reached by the actual iterations; the dashed blue line is the theoretical minimum. Use both the energy gap and distance to the target subspace to judge convergence.')}</p></section><section class="panel variational-derivation">${header(say('限制條件為什麼帶出特徵向量？','Why do constraints produce eigenvectors?'))}<div class="variational-explanation-grid"><article><h4>${say('1. 排除零函數與尺度','1. Remove the zero function and scaling')}</h4>${tex(String.raw`R(f)=\frac{f^{\mathsf T}L_0f}{f^{\mathsf T}f},\qquad f\ne0`,true)}<p>${say('只最小化能量，零函數就會勝出。固定長度為 1，相當於比較 Rayleigh 商。此時常數方向仍有零能量。','Minimizing energy alone allows the zero function. Fixing unit length compares the Rayleigh quotient instead; the constant direction still has zero energy.')}</p></article><article><h4>${say('2. 排除常數方向','2. Exclude the constant direction')}</h4>${tex(String.raw`f^{\mathsf T}\mathbf1=0,\qquad f^{\mathsf T}f=1`,true)}<p>${say('平均值為零不代表每個值都為零，而是正負值總和互相抵銷。單位長度則防止函數縮成零。','Zero mean does not mean every value is zero: positive and negative values balance. Unit length prevents collapse to zero.')}</p></article><article><h4>${say('3. 求能量的駐點','3. Find a stationary point')}</h4>${tex(String.raw`\mathcal L(f)=f^{\mathsf T}L_0f-\lambda(f^{\mathsf T}f-1)-\mu\mathbf1^{\mathsf T}f`,true)}${tex(String.raw`2L_0f-2\lambda f-\mu\mathbf1=0\ \Longrightarrow\ L_0f=\lambda f`,true)}<p>${say('因為 L₀ 的各列和為零，加上平均值限制可得 μ = 0。駐點滿足特徵方程；全域最小值才是 λ₂。','The rows of L₀ sum to zero, and the mean constraint gives μ = 0. Stationary points satisfy the eigenvalue equation; only the global minimum equals λ₂.')}</p></article><article><h4>${say('4. 回到 02 的 Fiedler 向量','4. Return to the Fiedler vector in 02')}</h4>${tex(String.raw`\lambda_2=\min_{f\perp\mathbf1,\ \|f\|_2=1}f^{\mathsf T}L_0f`,true)}<p>${say('連通圖上，它在跨越弱連線時可以有較大的值差，因此能呈現瓶頸。若 λ₂ 重複，解是一個子空間；不連通圖則可能有多個零能量解。','In a connected graph, a larger change can occur across a weak edge at little energy cost, revealing a bottleneck. A repeated λ₂ gives a subspace of solutions; disconnected graphs can have several zero-energy solutions.')}</p></article></div></section>${continuousComparison()}`;}
 function continuousComparison(){return `<section class="panel variational-continuous">${header(say('從有限維變分觀點，走向函數空間','From finite-dimensional variation to function spaces'))}<p class="panel-description">${say('目前仍在有限維空間 Rⁿ 做最佳化。「泛函」是把整個函數映射成一個能量值；真正的無限維問題，才需要選擇函數空間並處理邊界條件。','This is still optimization in finite-dimensional Rⁿ. A functional maps a whole function to a scalar energy. Infinite-dimensional problems additionally require a function space and boundary conditions.')}</p><div class="variational-table-scroll"><table class="variational-table variational-comparison"><thead><tr><th>${say('對照','Concept')}</th><th>${say('有限圖','Finite graph')}</th><th>${say('連續區域','Continuous domain')}</th></tr></thead><tbody>${[[say('函數空間','Function space'),String.raw`f\in\mathbb R^n`,String.raw`f\in H^1(\Omega)`],[say('局部變化','Local change'),String.raw`f_i-f_j`,String.raw`\nabla f`],[say('Dirichlet 能量','Dirichlet energy'),String.raw`\sum_{\{i,j\}\in E}w_{ij}(f_i-f_j)^2`,String.raw`\int_\Omega|\nabla f|^2\,dx`],[say('非負算子','Nonnegative operator'),String.raw`L_0`,String.raw`-\Delta`],[say('歸一化與正交','Normalization and orthogonality'),String.raw`\sum_i f_i^2=1,\quad\sum_i f_i=0`,String.raw`\int_\Omega f^2\,dx=1,\quad\int_\Omega f\,dx=0`]].map(([title,discrete,continuous])=>`<tr><th scope="row">${title}</th><td>${tex(discrete)}</td><td>${tex(continuous)}</td></tr>`).join('')}</tbody></table></div><p class="panel-description">${say('這個連續對照採用有界、連通且具 Lipschitz 邊界的區域，以及 Neumann 自然邊界條件。H¹ 表示函數與一階弱導數都平方可積；它允許常數，所以常數是零特徵值模態；若改用 H₀¹ 的 Dirichlet 邊界條件，就不能照搬這個結論。網格离散化還需要指定權重與質量矩陣，不能把圖矩陣直接等同於任意曲面的 Laplace 算子。','This comparison uses a bounded, connected domain with Lipschitz boundary and natural Neumann conditions. H¹ contains square-integrable functions with square-integrable first weak derivatives. It permits constants, giving a zero mode. This conclusion does not transfer to Dirichlet conditions in H₀¹. A mesh discretization also requires weights and a mass matrix; a graph matrix is not automatically the Laplace operator of an arbitrary surface.').replace('离散化','離散化')} <a href="https://math.mcgill.ca/gantumur/math580f13/laplacian.pdf" target="_blank" rel="noopener noreferrer">${say('Neumann 與 Dirichlet 譜的講義 ↗','Notes on Neumann and Dirichlet spectra ↗')}</a></p></section>`;}
 function drawFunction(values){
  const details=V.energyDetails(a,values),peak=Math.max(.01,...details.edges.map(e=>e.energy)),scale=Math.max(1,...values.map(Math.abs));
  const xs=g.nodes.map(p=>p.x),ys=g.nodes.map(p=>p.y),xMin=Math.min(...xs),xMax=Math.max(...xs),yMin=Math.min(...ys),yMax=Math.max(...ys);
  const positions=g.nodes.map(p=>({x:65+(p.x-xMin)/(xMax-xMin||1)*590,y:yMax===yMin?106:45+(p.y-yMin)/(yMax-yMin)*115}));
  $('variational-graph').innerHTML=details.edges.map(e=>{const p=positions[e.a],q=positions[e.b];return `<line x1="${p.x}" y1="${p.y}" x2="${q.x}" y2="${q.y}" stroke="#aa966e" stroke-opacity=".7" stroke-width="${1.5+5*e.energy/peak}"><title>${e.a+1} ↔ ${e.b+1}: ${energyText} ${fmt(e.energy,5)}</title></line>${n<=6?`<text x="${(p.x+q.x)/2}" y="${(p.y+q.y)/2-15}" text-anchor="middle" fill="#b6c8e2" font-size="14">w = ${fmt(e.w,2)}</text>`:''}`;}).join('')+positions.map((p,i)=>`<g><circle cx="${p.x}" cy="${p.y}" r="${n>25?8:13}" fill="${color(values[i],scale)}" stroke="#b9cdea" stroke-opacity=".5"/><text x="${p.x}" y="${p.y-24}" text-anchor="middle" fill="#c2d1e8" font-size="${n>25?12:16}">${i+1}</text>${n<=20?`<text x="${p.x}" y="${p.y+35}" text-anchor="middle" fill="#ecddbe" font-size="16">${fmt(values[i],2)}</text>`:''}<title>${nodeText} ${i+1}: ${fmt(values[i],5)}</title></g>`).join('');
  const px=i=>60+i*605/Math.max(1,n-1),py=value=>90-value/scale*61;
  $('variational-values').innerHTML=`<path d="M60 20V159H674" fill="none" stroke="#516c94"/><path d="M60 90H674" stroke="#6580a5" stroke-dasharray="4 5"/><text x="38" y="95" fill="#aebfd6" font-size="14">0</text><text x="37" y="32" fill="#aebfd6" text-anchor="end" font-size="14">${fmt(scale,1)}</text><text x="37" y="157" fill="#aebfd6" text-anchor="end" font-size="14">${fmt(-scale,1)}</text><path d="${values.map((x,i)=>`${i?'L':'M'}${px(i)} ${py(x)}`).join(' ')}" stroke="#ddbc7c" fill="none" stroke-width="2"/>${values.map((x,i)=>`<circle cx="${px(i)}" cy="${py(x)}" r="4" fill="${color(x,scale)}"><title>${nodeText} ${i+1}: ${fmt(x,5)}</title></circle>${n<=20||i%Math.ceil(n/15)===0?`<text x="${px(i)}" y="181" text-anchor="middle" fill="#acbfdc" font-size="14">${i+1}</text>`:''}`).join('')}<text x="675" y="199" text-anchor="end" fill="#9fb4d4" font-size="12">${say('節點編號','Node index')}</text>`;
  return details;
 }
 function updateSmooth(){
  const f=s.smoothValues[smoothKey],details=drawFunction(f);
  f.forEach((x,i)=>$('function-node-output-'+i).textContent=fmt(x,2));
  $('function-total').innerHTML=tex('E[f]='+fmt(details.total,4));
  $('function-edge-rows').innerHTML=details.edges.map(e=>`<tr><th scope="row">${e.a+1} ↔ ${e.b+1}</th><td>${fmt(e.w,3)}</td><td>${fmt(f[e.a],2)} − (${fmt(f[e.b],2)}) = ${fmt(e.difference,2)}</td><td><strong>${fmt(e.energy,4)}</strong><span class="variational-edge-track"><i style="width:${details.total?e.energy/details.total*100:0}%"></i></span></td></tr>`).join('')||`<tr><td colspan="4">${say('沒有連線，因此能量為零。','There are no edges, so energy is zero.')}</td></tr>`;
  save();
 }
 function resetDescent(){s.descentValues=V.initialize(n,s.descentSeed||7)||[];s.descentIteration=0;s.descentHistory=n>1?[V.energyDetails(a,s.descentValues).total]:[];s.descentGraphKey=graphKey;}
 function updateDescent(){
  const d=V.diagnostics(a,s.descentValues,target);drawFunction(s.descentValues.length===n?s.descentValues:Array(n).fill(0));
  const metric=(label,value,help='')=>`<div><span>${label}${help?`<small>${help}</small>`:''}</span><strong>${value}</strong></div>`;
  $('descent-metrics').innerHTML=metric(say('迭代次數','Iterations'),s.descentIteration)+metric(energyText,fmt(d.energy,6))+metric(say('理論最小值','Theoretical minimum'),target.value===null?'—':tex(String.raw`\lambda_2=`+fmt(target.value,6)))+metric(say('離最小值還有多少','Energy above minimum'),d.feasible?fmt(Math.max(0,d.energy-target.value),6):'—')+metric(say('到最小解子空間的距離','Distance to minimizing subspace'),d.feasible?fmt(d.distance,6):'—',say('0 表示已到達，正負號與重複模態都視為同一組解','0 means reached; sign and repeated modes are treated together'))+metric(say('特徵方程殘差','Eigen-equation residual'),d.feasible?fmt(d.residual,6):'—')+metric(say('目前平均 / 長度','Current mean / norm'),`${fmt(d.mean,3)} / ${fmt(d.norm,3)}`);
  const converged=d.feasible&&d.distance<1e-6&&d.residual<1e-6;
  const status=!d.feasible?say('少於 2 個節點時，平均為零與長度為 1 無法同時成立。請換教學例或新增節點。','With fewer than two nodes, zero mean and unit norm are incompatible. Choose a teaching example or add nodes.'):converged?say('已到達最低能量子空間。這是限制條件下的最平滑函數；整體換號仍是同一個解。','Reached the lowest-energy subspace: a smoothest function under the constraints. Reversing every sign is also a solution.'):d.residual<1e-9?say('目前停在其他駐點，尚未達到最小值。起點若缺少最低模態，可能發生這種情況；請換一組起點。','At another stationary point, not the minimum. An initial vector without a lowest-mode component can do this; try a new start.'):running?say('正在迭代：相鄰值的差異逐漸變小，同時保留平均為零、長度為 1。','Iterating: adjacent differences decrease while mean stays zero and norm stays one.'):say('按「走一步」看一次更新，或連續迭代觀察能量下降。','Take one step to inspect an update, or run the iterations to watch energy decrease.');
  $('descent-status').textContent=status;
  $('descent-run').textContent=running?say('暫停','Pause'):say('連續迭代','Run');
  $('descent-step').disabled=!d.feasible||running;$('descent-run').disabled=!d.feasible;
  const history=s.descentHistory,min=target.value||0,max=Math.max(min+1e-6,...history),px=i=>72+i*778/Math.max(1,history.length-1),py=x=>28+155*(max-x)/(max-min);
  $('descent-history').innerHTML=`<path d="M72 22V188H853" fill="none" stroke="#566f91"/><path d="M72 ${py(min)}H853" stroke="#83a7ff" stroke-dasharray="5 5"/><path d="${history.map((x,i)=>`${i?'L':'M'}${px(i)} ${py(x)}`).join(' ')}" fill="none" stroke="#e2bf7e" stroke-width="2.5"/><text x="60" y="34" text-anchor="end" fill="#b4c6df" font-size="14">${fmt(max,3)}</text><text x="60" y="187" text-anchor="end" fill="#b4c6df" font-size="14">${fmt(min,3)}</text><text x="72" y="214" fill="#b4c6df" font-size="14">${Math.max(0,s.descentIteration-history.length+1)}</text><text x="850" y="214" text-anchor="end" fill="#b4c6df" font-size="14">${s.descentIteration} ${say('步','steps')}</text>`;
  save();return {converged,stationary:d.residual<1e-9};
 }
 function takeStep(){if(n<2)return;s.descentValues=V.step(a,s.descentValues);s.descentIteration++;s.descentHistory.push(V.energyDetails(a,s.descentValues).total);if(s.descentHistory.length>1001)s.descentHistory.shift();}
 function stop(){running=false;clearTimeout(timer);}
 function tick(){if(!active||!running)return;for(let i=0;i<3;i++)takeStep();const result=updateDescent();if(result.converged||result.stationary){stop();updateDescent();return;}timer=setTimeout(tick,100);}
 $('variational-source').onchange=e=>{stop();s[sourceKey]=e.target.value;save();rerender();};
 if(isDescent){
  if(s.descentGraphKey!==graphKey||s.descentValues?.length!==n||s.descentValues.some(x=>!Number.isFinite(x))||!Array.isArray(s.descentHistory)||(n>1&&(Math.abs(Math.hypot(...s.descentValues)-1)>1e-7||Math.abs(s.descentValues.reduce((sum,x)=>sum+x,0))>1e-7)))resetDescent();
  $('descent-step').onclick=()=>{takeStep();updateDescent();};
  $('descent-run').onclick=()=>{if(running){stop();updateDescent();}else{running=true;updateDescent();timer=setTimeout(tick,100);}};
  $('descent-reset').onclick=()=>{stop();resetDescent();updateDescent();};
  $('descent-new').onclick=()=>{stop();s.descentSeed=(s.descentSeed||7)+1;resetDescent();updateDescent();};
  updateDescent();
 }else{
  g.nodes.forEach((_,i)=>$('function-node-'+i).oninput=e=>{s.smoothValues[smoothKey][i]=+e.target.value;updateSmooth();});
  document.querySelectorAll('[data-function-preset]').forEach(button=>button.onclick=()=>{const kind=button.dataset.functionPreset;s.smoothValues[smoothKey]=g.nodes.map((_,i)=>kind==='constant'?1:kind==='alternating'?(i%2?-1:1):n<=5?1+.1*i:1+.4*i/(n-1));s.smoothValues[smoothKey].forEach((x,i)=>$('function-node-'+i).value=x);updateSmooth();});
  updateSmooth();
 }
 const cards=isDescent?[[say('梯度決定下降方向','The gradient sets the descent direction'),String.raw`\nabla E[f]=2L_0f`,say('用目前的函數計算梯度，不直接把特徵向量當成動畫終點。','The update uses the current function’s gradient; it does not interpolate toward a precomputed eigenvector.')],[say('投影，再正規化','Project, then normalize'),String.raw`h=f-\eta\,2L_0f,\quad\widetilde h=h-\overline h\mathbf1,\quad f^+=\frac{\widetilde h}{\|\widetilde h\|_2}`,say('本例選 η = 0.45 / λₘₐₓ，讓更新穩定下降。若起點完全沒有最低模態的成分，可能收斂到其他駐點。','Here η = 0.45 / λₘₐₓ gives stable energy descent. An initial function with no lowest-mode component may converge to another stationary point.')]]:[[say('向量就是圖上的函數','A vector is a function on the graph'),String.raw`f:V\to\mathbb R,\qquad f=(f_1,\ldots,f_n)^{\mathsf T}`,say('每個節點是一個輸入，節點上的實數是輸出。不需要先有平面上的連續曲線。','Each node is an input and its real value is the output. A continuous curve in the plane is not required.')],[say('低特徵值的平滑含義','What smoothness means for low eigenvalues'),String.raw`L_0v_r=\lambda_rv_r\quad\Longrightarrow\quad\frac{v_r^{\mathsf T}L_0v_r}{v_r^{\mathsf T}v_r}=\lambda_r`,say('固定長度後，特徵值就是這個模態的能量。這把 04 看見的平緩與震盪，接回可以計算的量。','After fixing length, an eigenvalue is the mode’s energy. The smooth and oscillatory patterns seen in 04 now have a measurable meaning.')]];
 $('math-section').innerHTML=`<div class="math-heading"><span>✧</span><h3>${say('Behind the Spectrum','Behind the Spectrum')}</h3></div><div class="math-cards">${cards.map(([title,formula,body],i)=>`<article class="math-card"><span class="step">0${i+1}</span><h4>${title}</h4><div class="formula">${tex(formula,true)}</div><p>${body}</p></article>`).join('')}</div>`;
 return cleanup;
}
window.VariationalLabView={render,cleanup};
})();
