const test=require('node:test'),assert=require('node:assert/strict'),M=require('../js/math.js'),S=require('../js/signal-math.js'),Session=require('../js/session.js');
const near=(a,b,eps=1e-8)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`),types=['unnormalized','symmetric','randomwalk'];
function fixture(){const g=M.preset('star');g.edges.forEach((e,i)=>e.w=.2+i*.45);g.nodes.push({x:0,y:0});return g;}
test('all Laplacian Fourier bases reconstruct a nontrivial signal, including an isolated node',()=>{const g=fixture(),f=g.nodes.map((_,i)=>Math.sin(i*.8)+i*.04);for(const type of types){const a=M.analyze(g.nodes,g.edges,type),r=S.process(a,f,type,{kind:'truncate',modes:f.length});r.output.forEach((x,i)=>near(x,f[i]));near(r.energy,r.modalEnergy.reduce((a,b)=>a+b,0));near(r.fullError,0);near(r.error,0);}});
test('random-walk transform uses its weighted dual basis, not the incorrect Euclidean projection',()=>{const g=fixture(),a=M.analyze(g.nodes,g.edges,'randomwalk'),f=g.nodes.map((_,i)=>i===0?1:0),good=S.transform(a,f,'randomwalk'),wrong=a.vectors.map(v=>v.reduce((sum,x,i)=>sum+x*f[i],0));assert.ok(good.coefficients.some((x,i)=>Math.abs(x-wrong[i])>.1));S.reconstruct(a,good.coefficients).forEach((x,i)=>near(x,f[i]));});
test('truncation at zero returns zero and increasing retained modes reduces weighted reconstruction error',()=>{const g=fixture(),f=g.nodes.map((_,i)=>Math.cos(i));for(const type of types){const a=M.analyze(g.nodes,g.edges,type);let last=Infinity;for(let m=0;m<=f.length;m++){const r=S.process(a,f,type,{kind:'truncate',modes:m}),error=f.reduce((sum,x,i)=>sum+r.metric[i]*(x-r.output[i])**2,0);assert.ok(error<=last+1e-9);last=error;if(!m)assert.ok(r.output.every(x=>x===0));}}});
test('heat at zero is identity, high-pass at zero vanishes, and complementary filters sum to the input',()=>{const g=fixture(),f=g.nodes.map((_,i)=>Math.sin(i));for(const type of types){const a=M.analyze(g.nodes,g.edges,type);for(const tau of [0,.3,2]){const low=S.process(a,f,type,{kind:'heat',tau}),high=S.process(a,f,type,{kind:'highpass',tau});low.output.forEach((x,i)=>near(x+high.output[i],f[i]));if(!tau){low.output.forEach((x,i)=>near(x,f[i]));high.output.forEach(x=>near(x,0));}assert.ok(low.outputFrequencyEnergy<=low.frequencyEnergy+1e-9);}}});
test('heat keeps the stationary mode for each normalization and preserves isolated signals',()=>{const g=fixture();for(const type of types){const a=M.analyze(g.nodes,g.edges,type),f=a.degree.map(d=>type==='symmetric'&&d>0?Math.sqrt(d):1),r=S.process(a,f,type,{kind:'heat',tau:3});r.output.forEach((x,i)=>near(x,f[i]));}});
test('ideal filter treats a repeated eigenspace as one frequency',()=>{const g=M.preset('complete'),a=M.analyze(g.nodes,g.edges),f=g.nodes.map((_,i)=>i),r=S.process(a,f,'unnormalized',{kind:'ideal',cutoff:1});r.output.forEach(x=>near(x,3.5));assert.deepEqual(r.gains,[1,0,0,0,0,0,0,0]);});
test('graph signals and filtering settings persist while undo retains per-node signal values',()=>{const s=Session.create(M);s.graph.nodes.forEach((p,i)=>p.signal=.5*i);s.spectralSignal={...s.spectralSignal,filter:'highpass',tau:2.5,modes:2};Session.checkpoint(s);s.graph.nodes[0].signal=-2;Session.undo(s);near(s.graph.nodes[0].signal,0);const restored=Session.create(M);assert.ok(Session.restore(restored,JSON.parse(JSON.stringify(Session.snapshot(s)))));assert.deepEqual(restored.spectralSignal,s.spectralSignal);assert.deepEqual(restored.graph.nodes,s.graph.nodes);});
test('empty and single-node signal transforms stay finite',()=>{for(const type of types)for(const n of [0,1]){const a=M.analyze(Array.from({length:n},()=>({})),[],type),f=Array(n).fill(1),r=S.process(a,f,type,{kind:'heat',tau:1});assert.equal(r.output.length,n);r.output.forEach(x=>near(x,1));assert.ok(Number.isFinite(r.fullError));}});
