const test=require('node:test'),assert=require('node:assert/strict'),M=require('../js/math.js'),V=require('../js/variational-math.js');
const near=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
const analyze=kind=>{const g=V.teachingGraph(kind);return M.analyze(g.nodes,g.edges);};
test('five-node smooth and alternating examples match both edge sum and quadratic form',()=>{const a=analyze('path5');for(const [f,expected] of [[[1,1.1,1.2,1.3,1.4],.04],[[1,-1,1,-1,1],16]]){const e=V.energyDetails(a,f);near(e.total,expected);near(e.quadratic,expected);assert.equal(e.edges.length,4);}});
test('Dirichlet energy ignores constants and scales quadratically in amplitude and linearly in weights',()=>{const g=V.teachingGraph('bridge6'),a=M.analyze(g.nodes,g.edges),f=[.2,-.7,.9,1.1,-.3,.8],e=V.energyDetails(a,f).total;near(V.energyDetails(a,f.map(x=>x+10)).total,e);near(V.energyDetails(a,f.map(x=>3*x)).total,9*e);near(V.energyDetails(M.analyze(g.nodes,g.edges.map(e=>({...e,w:e.w*2}))),f).total,2*e);near(V.energyDetails(a,Array(6).fill(2)).total,0);});
test('descent preserves mean-zero/unit constraints, decreases energy, and converges on weak bridge',()=>{const a=analyze('bridge6'),target=V.targetSpace(a);let f=V.initialize(6,7),previous=Infinity;for(let i=0;i<500;i++){const d=V.diagnostics(a,f,target);near(d.mean,0);near(d.norm,1);assert.ok(d.energy<=previous+1e-11);previous=d.energy;f=V.step(a,f);}const final=V.diagnostics(a,f,target);near(final.energy,a.values[1]);assert.ok(final.distance<1e-6);assert.ok(final.residual<1e-6);});
test('target comparison ignores eigenvector sign and handles repeated positive eigenvalues',()=>{const g=M.preset('complete'),a=M.analyze(g.nodes,g.edges),target=V.targetSpace(a),f=V.initialize(g.nodes.length,2);assert.equal(target.dimension,g.nodes.length-1);near(V.diagnostics(a,f,target).distance,0,1e-7);near(V.diagnostics(a,f.map(x=>-x),target).distance,0,1e-7);near(V.diagnostics(a,V.step(a,f),target).energy,g.nodes.length);});
test('disconnected graphs converge to mean-zero component constants with zero energy',()=>{const nodes=Array.from({length:5},()=>({})),a=M.analyze(nodes,[{a:0,b:1,w:2},{a:2,b:3,w:1}]),target=V.targetSpace(a);assert.equal(target.value,0);assert.equal(target.dimension,2);let f=V.initialize(5,3);for(let i=0;i<400;i++)f=V.step(a,f);const d=V.diagnostics(a,f,target);near(d.energy,0);assert.ok(d.distance<1e-7);near(f[0],f[1]);near(f[2],f[3]);});
test('deterministic initialization and isolated / infeasible graph cases remain explicit',()=>{assert.deepEqual(V.initialize(5,7),V.initialize(5,7));assert.notDeepEqual(V.initialize(5,7),V.initialize(5,8));assert.equal(V.projectNormalize([1,1]),null);for(const n of [0,1]){const a=M.analyze(Array.from({length:n},()=>({})),[]);assert.equal(V.initialize(n),null);assert.equal(V.step(a,Array(n).fill(1)),null);assert.equal(V.diagnostics(a,null).feasible,false);assert.equal(V.targetSpace(a).value,null);}const a=M.analyze([{},{}],[]),f=V.initialize(2);assert.deepEqual(V.step(a,f),f);near(V.diagnostics(a,f).distance,0,1e-7);});
test('both bilingual teaching views render formulas, preserve the drawing, and cancel a running iteration on exit',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),katex=require('../assets/vendor/katex/katex.min.js'),Session=require('../js/session.js'),source=fs.readFileSync(require.resolve('../js/variational-view.js'),'utf8');
 for(const lang of ['zh','en'])for(const module of ['smoothness','variational'])for(const kind of ['path5','bridge6','empty','single','shared']){
  const graph=kind==='empty'?{nodes:[],edges:[]}:kind==='single'?{nodes:[{x:20,y:30}],edges:[]}:V.teachingGraph('bridge6'),state=Session.create(M,graph);state.lang=lang;state.module=module;state.type='randomwalk';state.variationalLab.smoothSource=state.variationalLab.descentSource=['path5','bridge6'].includes(kind)?kind:'shared';
  const before=JSON.stringify(state.graph),elements=new Map(),formulas=[],timers=new Map();let timerId=0;
  const $=id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id);};
  const context={window:{VariationalMath:V,LabSession:Session},document:{querySelectorAll:()=>[]},setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id)};vm.runInNewContext(source,context);
  const cleanup=context.window.VariationalLabView.render({state,M,$,tex:(equation,displayMode=false)=>{formulas.push(equation);return katex.renderToString(equation,{displayMode,throwOnError:true,strict:'error'});},fmt:(x,d=3)=>Number.isFinite(x)?x.toFixed(d):'—',header:title=>`<h3>${title}</h3>`,svg:()=>'',color:()=>'',save(){},rerender(){}});
  assert.equal(JSON.stringify(state.graph),before);assert.equal(state.type,'randomwalk');assert.ok(formulas.length>5);assert.ok(formulas.every(f=>!/[\r\n\t]/.test(f)));
  if(module==='variational'&&!['empty','single'].includes(kind)){$('descent-run').onclick();assert.equal(timers.size,1);cleanup();assert.equal(timers.size,0);}else cleanup();
 }
});
test('smoothness view shows the intermediate Dirichlet-energy expansion',()=>{const source=require('node:fs').readFileSync(require.resolve('../js/variational-view.js'),'utf8');assert.match(source,/f\^\{\\mathsf T\}\(D-A\)f/);assert.match(source,/d_i=\\sum_jw_\{ij\}/);assert.match(source,/f_i\^2-2f_if_j\+f_j\^2/);});
